/**
 * LA DIRECTION ARTISTIQUE DES 54 MAGAZINES
 *
 * Cinquante-quatre fois la même revue, cinquante-quatre personnalités
 * différentes. Chaque entrée dit **comment cette semaine-là traite les sept
 * chapitres** : la matière, le motif qui revient d'un chapitre à l'autre, la
 * lumière, la palette, la scène de couverture, et **les sept sujets**, un par
 * chapitre.
 *
 * C'est ce tableau — et lui seul — qui produit :
 *
 * 1. **les briefs d'image** (`scripts/faire-prompt-aime.ts`) — une phrase par
 *    image, la même pour tout le monde ;
 * 2. **le manifeste** de la bibliothèque (`npm run visuels`) — semaine,
 *    chapitre, titre, univers, saison, style, sujet, couleur, description,
 *    mots-clés ;
 * 3. **les replis** : quand une image n'est pas encore livrée, la palette et le
 *    titre de la semaine tiennent la couverture, sans jamais emprunter le
 *    visuel d'une autre semaine.
 *
 * ## La règle de la maison
 *
 * Le mariage est **le territoire**, pas le sujet. Une robe parle du mariage,
 * une architecture parle du mariage, une table, une chanson, un objet transmis
 * en parlent aussi. On ne montre donc pas 54 fois des mariés : on montre
 * **54 mondes** qui mènent tous au mariage.
 */

export interface DirectionDuMagazine {
  /** 1 à 54. */
  numero: number;
  /** Le titre de la semaine, comme un titre de numéro : « Testament corse ». */
  titre: string;
  /** La famille visuelle : « Méditerranée insulaire, documentaire ». */
  style: string;
  /** L'ancrage : lieux, cultures, époques dont la semaine se réclame. */
  terroir: string;
  /** Les matières : ce qu'on doit pouvoir toucher du regard. */
  matiere: string;
  /** Le motif qui revient dans les sept chapitres — la cohérence de la semaine. */
  motif: string;
  /** La lumière de la semaine, dite comme on la décrit à un chef opérateur. */
  lumiere: string;
  /** Les deux couleurs de la semaine : le fond éditorial, et l'accent. */
  palette: { fond: string; accent: string };
  /** Ce que doit montrer la couverture — un monde, pas un mariage. */
  coverSujet: string;
  /** Les sept sujets, dans l'ordre des chapitres (01 → 07). */
  chapitres: string[];
}

/** Le tableau des 54 numéros, dans l'ordre du magazine. */
export const DIRECTIONS: DirectionDuMagazine[] = [
  /* ——————————————————————————————— L'HIVER ——————————————————————————————— */
  {
    numero: 1,
    titre: 'Blanc minéral',
    style: 'Minimalisme nordique, éditorial',
    terroir: 'un fjord, une maison basse, un atelier de pierre',
    matiere: 'calcaire clair, laine non teintée, verre dépoli',
    motif: 'une seule ligne d’ombre sur un mur blanc',
    lumiere: 'lumière froide et verticale, dix heures du matin en janvier',
    palette: { fond: '#E9E9E4', accent: '#2F4358' },
    coverSujet:
      'un mur de calcaire clair frappé par une seule lame de lumière froide, un banc de bois, une couverture de laine pliée',
    chapitres: [
      'deux silhouettes de dos dans la neige tassée, les mains presque jointes',
      'un manteau de laine écrue au col sculptural, porté, visage hors cadre',
      'une maison basse de pierre au bord d’un fjord gelé, brume basse',
      'une table de bois brut, deux assiettes de grès, pain et beurre',
      'des lanternes de glace allumées à la nuit tombée',
      'des sabots de bois devant une porte, la neige accumulée',
      'un album de lin ouvert sur des tirages en noir et blanc',
    ],
  },
  {
    numero: 2,
    titre: 'L’atelier d’hiver',
    style: 'Documentaire de savoir-faire, matières',
    terroir: 'un atelier de relieur, un poêle, des mains qui travaillent',
    matiere: 'papier chiffon, cire, cuir, laiton terni',
    motif: 'les mains et l’outil, jamais le visage',
    lumiere: 'une lampe d’atelier, l’ombre chaude du poêle',
    palette: { fond: '#3B3129', accent: '#C08A4A' },
    coverSujet:
      'un établi d’atelier, un fer à dorer, des feuilles de papier chiffon et de la cire, la lumière d’une lampe unique',
    chapitres: [
      'quatre mains qui tiennent un même objet au-dessus de l’établi',
      'une doublure de costume posée à plat, épinglée sur le feutre',
      'un atelier vitré sous la neige, la lumière allumée à l’intérieur',
      'un moule à gâteau en cuivre et un saladier de fruits confits',
      'une contrebasse dans l’atelier vide, poussière dans la lumière',
      'des outils d’artisan suspendus, chacun à sa place',
      'des négatifs en train de sécher au fil, pinces de bois',
    ],
  },
  {
    numero: 3,
    titre: 'Chambre d’hôtes',
    style: 'Intérieur chaleureux, art de vivre',
    terroir: 'une maison de village, un feu de bois, la table du soir',
    matiere: 'lin lavé, céramique émaillée, bois ciré, laine bouclée',
    motif: 'le feu et ce qu’on met autour',
    lumiere: 'lumière de fin d’après-midi, lampes allumées avant la nuit',
    palette: { fond: '#6E4B3A', accent: '#E7C49B' },
    coverSujet:
      'une cheminée allumée dans une pièce basse, un fauteuil de laine, des bûches, la lumière orange sur la pierre',
    chapitres: [
      'deux tasses posées côte à côte sur un appui de fenêtre, la buée',
      'une robe de laine suspendue devant le feu, chaussons au sol',
      'la façade d’une maison de village, fenêtre éclairée, neige au toit',
      'un gratin qui sort du four, torchon de lin, table mise',
      'un coin de salon où l’on danse, tapis roulé contre le mur',
      'des chaussures alignées à l’entrée, manteaux accrochés',
      'un vieux livre d’or ouvert, signatures et dates à l’encre',
    ],
  },
  {
    numero: 4,
    titre: 'Le carnaval des glaces',
    style: 'Pop rétro, couleur assumée',
    terroir: 'une station de sports d’hiver, années 1980',
    matiere: 'nylon brillant, laine jacquard, néon, glace',
    motif: 'la couleur vive sur la neige, sans excuse',
    lumiere: 'lumière dure de midi sur la neige, ombres bleues',
    palette: { fond: '#7FB2E5', accent: '#E8467C' },
    coverSujet:
      'une rampe de neige éclairée par un néon rose, une combinaison de ski rétro posée sur un banc',
    chapitres: [
      'deux personnes qui se lancent une boule de neige, rires vrais',
      'une combinaison de ski jacquard, lunettes miroir, visage hors cadre',
      'un télésiège vide au-dessus d’un versant bleu, midi',
      'un plateau de fromages et un vin chaud, table de terrasse enneigée',
      'une piste de danse sous les guirlandes, doudounes sur les chaises',
      'un carnaval de village à la montagne, masques et cloches',
      'un appareil photo argentique rempli de neige, une pellicule exposée',
    ],
  },
  {
    numero: 5,
    titre: 'Bois & cuir',
    style: 'Matières nobles, intérieur patrimoine',
    terroir: 'une bibliothèque, un club anglais, un bureau ancien',
    matiere: 'chêne ciré, cuir patiné, feutre vert, laiton',
    motif: 'la patine : ce qui s’use dit ce qui dure',
    lumiere: 'lumière de lampe à abat-jour, reflets sur le cuir',
    palette: { fond: '#2E2A24', accent: '#A97C4B' },
    coverSujet:
      'une bibliothèque de chêne, un fauteuil de cuir, une lampe de laiton allumée, la poussière dans la lumière',
    chapitres: [
      'deux mains qui se serrent au-dessus d’un bureau ancien, contrat fermé',
      'une paire de souliers de cuir cousus main, patine visible',
      'un escalier de bois ciré montant vers la lumière d’une verrière',
      'un service de table en laiton et porcelaine, nappe de lin épais',
      'un gramophone et des 78 tours, aiguille posée sur le sillon',
      'des registres reliés cuir, étiquettes écrites à la main',
      'un coffret de bois verrouillé, lettres attachées d’un ruban',
    ],
  },
  {
    numero: 6,
    titre: 'Cinéma des années 60',
    style: 'Rétro cinéma, Technicolor',
    terroir: 'un studio, une avant-première, une pellicule 35 mm',
    matiere: 'velours, celluloïd, projecteur, paillettes',
    motif: 'le faisceau du projecteur et ce qu’il traverse',
    lumiere: 'lumière de plateau, contrastes francs, ombres portées',
    palette: { fond: '#7A1F2B', accent: '#E3B23C' },
    coverSujet:
      'un projecteur 35 mm allumé dans une salle vide, fauteuils de velours rouge, faisceau dans la fumée',
    chapitres: [
      'un couple qui s’embrasse à contre-jour sur un quai de gare de studio',
      'une robe fourreau de satin, gants longs posés sur le velours d’un fauteuil',
      'la façade lumineuse d’un cinéma de quartier, séance de minuit',
      'un chariot de pâtisseries d’avant-première, coupes de champagne',
      'un orchestre de bal, micros anciens, robes à crinolines',
      'une affiche peinte à la main collée sur un mur de studio',
      'des boîtes de pellicule étiquetées, négatifs tenus à la lumière',
    ],
  },
  {
    numero: 7,
    titre: 'Lettres d’hiver',
    style: 'Papeterie et archives',
    terroir: 'un secrétaire, un bureau d’écriture, la poste d’hiver',
    matiere: 'papier vergé, encre noire, cachet de cire, ficelle',
    motif: 'l’écriture : une main, une plume, un pli',
    lumiere: 'lumière rasante de fenêtre, papier surexposé',
    palette: { fond: '#F2EDE4', accent: '#1F2B4D' },
    coverSujet:
      'un secrétaire ouvert, plume trempée, feuille commencée, cachet de cire et ficelle sur le bois',
    chapitres: [
      'deux lettres écrites par deux mains différentes, posées côte à côte',
      'un mouchoir brodé aux initiales, posé sur un papier d’enveloppe',
      'une boîte aux lettres de campagne sous la neige, porte entrouverte',
      'une étiquette de bouteille calligraphiée à la plume',
      'un programme de bal calligraphié, ruban passé autour',
      'des cartes postales anciennes étalées, tampons de plusieurs pays',
      'un buvard taché d’encre, une plume posée à côté',
    ],
  },
  {
    numero: 8,
    titre: 'Après-ski',
    style: 'Sport chic, montagne',
    terroir: 'un chalet de haute altitude, une station, la nuit qui tombe',
    matiere: 'laine, fourrure écrue, cuir, bois fumé',
    motif: 'la chaleur après le froid : ce qu’on enlève en rentrant',
    lumiere: 'bleu de nuit sur la neige, jaune chaud aux fenêtres',
    palette: { fond: '#2A3C4E', accent: '#D9A15B' },
    coverSujet:
      'un chalet éclairé dans la nuit bleue, skis plantés dans la neige, fumée à la cheminée',
    chapitres: [
      'deux personnes qui se tiennent les mains devant un feu de chalet, moufles au sol',
      'une chapka et un col de fourrure, une peau rougie par le froid',
      'la terrasse d’un refuge à 2 000 mètres, drapeaux de neige au vent',
      'une fondue servie sur une table de bois, pain coupé, vin blanc',
      'un bar de station, lumières ambrées, quelqu’un danse encore',
      'des bouteilles de liqueur de montagne étiquetées à la main',
      'un carnet d’altitude, tampons de refuges, photos collées',
    ],
  },
  {
    numero: 9,
    titre: 'Noir givré',
    style: 'Noir & blanc documentaire',
    terroir: 'une ville d’hiver, un quai, une gare de nuit',
    matiere: 'béton gelé, acier, laine sombre, glace sale',
    motif: 'le graphisme du blanc et du noir : silhouettes, arêtes',
    lumiere: 'lumière dure sans couleur, contraste poussé, grain visible',
    palette: { fond: '#111114', accent: '#DADADA' },
    coverSujet:
      'un quai de gare gelé en noir et blanc, vapeur d’un train, une silhouette de dos, très contrasté',
    chapitres: [
      'deux silhouettes qui se rejoignent dans une gare, vues de très loin',
      'une main gantée sur une manche de laine sombre, gros plan',
      'des marches de béton, neige tassée, géométrie de la ville',
      'un café noir posé sur un comptoir de zinc, reflet du néant',
      'un saxophone au repos contre une chaise de club vide',
      'un marché de nuit, fumée, guirlandes électriques en gris',
      'des planches-contacts annotées au crayon gras',
    ],
  },
  {
    numero: 10,
    titre: 'La maison de famille',
    style: 'Intérieur patrimoine, portrait d’intérieur',
    terroir: 'une maison transmise, un escalier de pierre, un salon jamais refait',
    matiere: 'pierre, tapisserie fanée, argenterie, bois sombre',
    motif: 'ce qui était là avant nous : les murs, les portraits, l’usure',
    lumiere: 'lumière poussiéreuse de fin d’après-midi, rideaux tirés',
    palette: { fond: '#4A4238', accent: '#C9A227' },
    coverSujet:
      'un grand salon jamais refait, tapisserie fanée, portraits encadrés, une seule lampe allumée',
    chapitres: [
      'trois générations autour d’une même table, les mains, pas les visages',
      'une robe d’époque sortie de sa housse, dentelle fragile',
      'un escalier de pierre usé, main courante de fer forgé',
      'un argenterie de famille, nappe brodée, bougies allumées',
      'un piano droit dans le salon vide, couvercle ouvert',
      'des armoiries familiales gravées dans la pierre d’un linteau',
      'une boîte de photos jaunies, portraits identifiés au dos',
    ],
  },
  {
    numero: 11,
    titre: 'Mille et une nuits d’hiver',
    style: 'Orient contemporain, éditorial',
    terroir: 'un riad, un hammam, une table de fête à la lueur des lanternes',
    matiere: 'laiton repoussé, zellige, soie, verre teinté',
    motif: 'la lumière qui traverse un motif découpé',
    lumiere: 'lueur chaude de lanternes, ombres dessinées au sol',
    palette: { fond: '#3A1F2E', accent: '#E0A458' },
    coverSujet:
      'une lanterne de laiton découpée allumée dans l’ombre, son motif projeté sur un mur de zellige',
    chapitres: [
      'un couple vu de dos dans un patio, mains jointes, fontaine au centre',
      'un caftan brodé main, fils d’or, étoffe posée sur du zellige',
      'un riad à l’aube, bassin calme, colonnes d’arcades',
      'un plateau de pâtisseries au miel et un thé versé de haut',
      'des percussions et un chant dans une cour, nuit complète',
      'des mains au henné, geste traditionnel filmé de près',
      'un coran de famille, marque-page de cuir, posé sur un lutrin',
    ],
  },
  {
    numero: 12,
    titre: 'Le bal des masques',
    style: 'Baroque nocturne, spectaculaire',
    terroir: 'un théâtre à l’italienne, un bal d’hiver, la nuit du solstice',
    matiere: 'velours, plumes, or terni, masques de Venise',
    motif: 'le masque : ce qu’on montre et ce qu’on cache',
    lumiere: 'bougies, clair-obscur, or qui accroche la lumière',
    palette: { fond: '#1A1220', accent: '#C9A227' },
    coverSujet:
      'un masque vénitien à plumes posé sur un velours noir, une seule bougie allumée à côté',
    chapitres: [
      'deux mains qui se cherchent derrière un loup de velours, gants noirs',
      'un costume brodé d’or sur un mannequin de couture, plumes au sol',
      'un théâtre à l’italienne vide, loges dorées, rideau levé',
      'une table de banquet dressée de bougies, verres noirs et or',
      'un orchestre masqué en pleine nuit, instruments dorés',
      'un défilé de masques dans une ruelle étroite, lanternes',
      'un programme de bal gravé, invitations cachetées à la cire',
    ],
  },

  /* ————————————————————————————— LE PRINTEMPS ————————————————————————————— */
  {
    numero: 13,
    titre: 'Jardin de curé',
    style: 'Botanique romantique, jardin français',
    terroir: 'un presbytère, un potager, un jardin de curé derrière le mur',
    matiere: 'terreau, zinc, terre cuite, fleurs coupées',
    motif: 'le désordre savant du jardin : rien n’est aligné, tout est juste',
    lumiere: 'lumière douce de fin avril, ciel laiteux',
    palette: { fond: '#8F9E6B', accent: '#B33A3A' },
    coverSujet:
      'un jardin de curé en désordre savant, arrosoir de zinc, un mur de pierre, pivoines coupées sur une planche',
    chapitres: [
      'deux mains qui se passent un bouquet cueilli à l’instant, terre sur les doigts',
      'un tablier de toile et un chapeau de paille, fleurs glissées dans la poche',
      'un potager clos de murs, allées de buis, un banc de pierre',
      'une table de jardin sous le poirier, tarte aux fruits et limonade',
      'une guirlande de fanions entre deux arbres, table dressée dehors',
      'un marché de plants, cageots, voix qui marchandent',
      'un herbier de feuilles séchées, étiquettes manuscrites',
    ],
  },
  {
    numero: 14,
    titre: 'Paris à l’aube',
    style: 'Street photographie, noir et blanc',
    terroir: 'les rues vides à six heures, un café qui ouvre, un quai de Seine',
    matiere: 'pavés mouillés, zinc, bitume, verre de café',
    motif: 'la ville avant les gens : traces, reflets, vapeur',
    lumiere: 'lumière rasante et grise, réverbères encore allumés',
    palette: { fond: '#2B2B2F', accent: '#D8CFC0' },
    coverSujet:
      'un boulevard parisien désert à l’aube, pavés mouillés, réverbères allumés, un vélo posé contre un mur',
    chapitres: [
      'deux silhouettes qui s’éloignent sous un porche, vues de dos',
      'un tailleur froissé par la nuit porté dans la rue, cadré de près',
      'une devanture de bistrot qui ouvre, chaises encore sur les tables',
      'un comptoir de zinc, deux cafés, croissants sur une assiette',
      'un club qui ferme, dernière cigarette devant la porte',
      'un livreur de journaux, cageots, un boucher qui lève son rideau de fer',
      'un photomaton et une bande de quatre photos oubliée',
    ],
  },
  {
    numero: 15,
    titre: 'Le tirage du printemps',
    style: 'Graphisme et impression, éditorial couleur',
    terroir: 'un atelier d’imprimerie, un risographe, une sérigraphie',
    matiere: 'papier recyclé, encre fluorescente, calque, rouleau',
    motif: 'la superposition : deux couleurs décalées font une troisième',
    lumiere: 'lumière blanche d’atelier, ombres franches sous la presse',
    palette: { fond: '#F4E7C5', accent: '#E8467C' },
    coverSujet:
      'une presse risographe et des tirages fraîchement empilés, encre fluorescente sur les rouleaux',
    chapitres: [
      'deux affiches personnalisées, deux écritures, côte à côte sur le mur',
      'un imprimé de robe sur un mannequin de papier, motifs découpés',
      'une ville vue en trois couleurs superposées, graphisme net',
      'un menu imprimé à la main, encre décalée, assiette posée dessus',
      'un flyer de concert sérigraphié, main qui le tend dans la foule',
      'des affiches de spectacles recouvrant un mur de rue',
      'une fresque collective signée par les invités, mains et pinceaux',
    ],
  },
  {
    numero: 16,
    titre: 'Lumière du Nord',
    style: 'Design scandinave, épure',
    terroir: 'un appartement clair, un lac, un pavillon d’architecte',
    matiere: 'hêtre clair, lin blanc, céramique mate, verre',
    motif: 'la ligne de bois et l’ombre nette sous chaque objet',
    lumiere: 'lumière blanche et diffuse de mai, très longue',
    palette: { fond: '#E7E4DC', accent: '#7E9AA6' },
    coverSujet:
      'un intérieur clair au parquet de hêtre, une table basse, une branche de cerisier dans un vase, ombres nettes',
    chapitres: [
      'deux personnes assises au sol, genoux qui se touchent, tasses à la main',
      'un ensemble en lin froissé, bijou d’argent minimal, cou et mains',
      'un pavillon de bois au bord d’un lac immobile, reflet parfait',
      'des gâteaux à la cardamome et du café clair sur une table de bois',
      'des bougies allumées en plein jour, fenêtre ouverte, rideau qui bouge',
      'une barque au bord du lac, gilets de sauvetage, matin',
      'des cartons de déménagement étiquetés, un cadre posé par terre',
    ],
  },
  {
    numero: 17,
    titre: 'Le grand ménage',
    style: 'Reportage documentaire, vie quotidienne',
    terroir: 'un appartement qu’on vide, une brocante, un marché du dimanche',
    matiere: 'cartons, poussière, faïence chinée, papier journal',
    motif: 'l’inventaire : ce qu’on garde, ce qu’on donne',
    lumiere: 'lumière de jour qui traverse une pièce vide, poussière visible',
    palette: { fond: '#C9C0AE', accent: '#2E6B54' },
    coverSujet:
      'une pièce en cours de tri, cartons ouverts, faïences séparées en deux piles, lumière de plein jour',
    chapitres: [
      'deux personnes qui hésitent devant une pile d’objets, une main posée sur l’autre',
      'une robe portée une fois, encore sur son cintre, à rendre ou à garder',
      'une maison qu’on vide, portes ouvertes, gravats dans l’entrée',
      'une table de débarras, assiettes dépareillées, confitures du dimanche',
      'une sono empruntée posée dans un salon, câbles au sol',
      'un étal de brocante, marchand qui discute, mains qui fouillent',
      'une boîte étiquetée « à garder », un ruban autour',
    ],
  },
  {
    numero: 18,
    titre: 'Roses anglaises',
    style: 'Anglais cottage chic, relecture contemporaine',
    terroir: 'un manoir du Sussex, un jardin clos, un thé à cinq heures',
    matiere: 'roses anciennes, chintz, porcelaine fine, gazon taillé',
    motif: 'la rose en pleine forme, pas en bouton',
    lumiere: 'lumière britannique douce, ciel couvert lumineux',
    palette: { fond: '#C4A7A0', accent: '#2F4A3C' },
    coverSujet:
      'un mur de manoir couvert de roses anciennes, une théière de porcelaine posée sur un muret, gazon taillé',
    chapitres: [
      'deux mains qui se tiennent dans une allée de jardin, roses au premier plan',
      'un tailleur de lin rose pâle, une broche ancienne, gros plan',
      'une véranda de manoir ouverte sur la pelouse après la pluie',
      'un thé complet à cinq heures, scones, confiture, porcelaine',
      'un pianiste dans un salon de campagne, fenêtres ouvertes',
      'des registres paroissiaux et une église de village dans les arbres',
      'un album de famille anglais, tirages collés aux coins',
    ],
  },
  {
    numero: 19,
    titre: 'L’opéra des fleurs',
    style: 'Floral spectaculaire, art contemporain',
    terroir: 'un marché aux fleurs, un atelier de fleuriste, une serre',
    matiere: 'pétales, tiges, eau, verre, fil de fer',
    motif: 'le volume : la fleur grandeur nature, jamais le bouquet sage',
    lumiere: 'lumière de serre, verte et filtrée',
    palette: { fond: '#4E6B4A', accent: '#E5643F' },
    coverSujet:
      'une serre entière de fleurs en pleine floraison, arrosoirs, eau au sol, lumière filtrée par le verre',
    chapitres: [
      'deux mains qui se tendent un bouquet plus grand que les bras',
      'des fleurs portées dans les cheveux et à la boutonnière, très gros plan',
      'une serre vitrée au milieu des champs, portes ouvertes',
      'un gâteau nu couvert de fleurs comestibles, couteau posé',
      'des pétales lancés en l’air au moment du bal, mouvement court',
      'un marché aux fleurs au petit matin, cageots et monnaie',
      'un herbier contemporain encadré, fleurs pressées et étiquettes',
    ],
  },
  {
    numero: 20,
    titre: 'Campagne française',
    style: 'Terroir, lumière de printemps',
    terroir: 'une ferme, une allée de tilleuls, un village de pierre',
    matiere: 'pierre blonde, tuile, lin, cuivre',
    motif: 'la ligne d’horizon : champs, clocher, tilleuls',
    lumiere: 'lumière rasante du soir sur les champs',
    palette: { fond: '#B9AE82', accent: '#5C6B3F' },
    coverSujet:
      'une allée de tilleuls menant à une ferme de pierre, chien de ferme, lumière du soir sur les champs',
    chapitres: [
      'trois générations devant la porte de la ferme, corps serrés',
      'une robe de lin brodée aux initiales, accrochée à une porte de grange',
      'un village de pierre endormi dans la brume de six heures',
      'une table de ferme sous les arbres, jambon, vin de pays, pain',
      'un bal musette dans la grange, guirlandes et accordéon',
      'une charrette fleurie qui traverse un village, cloches',
      'des photos punaisées dans la remise, souvenirs de moissons',
    ],
  },
  {
    numero: 21,
    titre: 'Néon pastoral',
    style: 'Surréalisme champêtre, pop',
    terroir: 'un champ de blé, un pré, la nuit tombée',
    matiere: 'blé, néon, plexiglas, herbe haute',
    motif: 'l’objet de ville posé dans la nature, sans explication',
    lumiere: 'crépuscule bleu et source électrique rose',
    palette: { fond: '#3A4A6B', accent: '#FF6FA5' },
    coverSujet:
      'une enseigne néon rose plantée au milieu d’un champ de blé au crépuscule, herbe haute, ciel bleu profond',
    chapitres: [
      'deux silhouettes assises dans les blés, néon allumé loin derrière',
      'une robe de satin rose éclairée au néon, tissu seul, aucun visage',
      'un pré avec un escalier de bois qui ne mène nulle part, nuit bleue',
      'une table dressée en plein champ, bougies, assiettes, néon rose',
      'une piste de danse en plein air dans l’herbe, lumières colorées',
      'une fête foraine vide au petit matin, guirlandes encore allumées',
      'un polaroïd posé dans l’herbe, image encore en train de se révéler',
    ],
  },
  {
    numero: 22,
    titre: 'Udaipur',
    style: 'Inde contemporaine, documentaire couleur',
    terroir: 'un palais lacustre, un bazar, une cérémonie au bord de l’eau',
    matiere: 'soie brodée, marbre, safran, cuivre',
    motif: 'l’eau et la couleur : un palais qui se reflète',
    lumiere: 'lumière blanche de fin d’après-midi, couleurs saturées',
    palette: { fond: '#C0562E', accent: '#1E6F7A' },
    coverSujet:
      'une façade de palais indien se reflétant dans un lac calme, barques, lumière de fin de journée',
    chapitres: [
      'deux mains qui versent l’une dans l’autre, fleurs de jasmin au poignet',
      'un sari brodé main, fils d’or, posé sur du marbre, bijoux à côté',
      'des escaliers de marbre plongeant dans un lac, aucune présence',
      'des plateaux de cuivre, épices, pâtisseries au safran',
      'des tambours et une foule en couleurs dans une cour de palais',
      'une cérémonie au bord de l’eau, pétales portés par le courant',
      'des enveloppes de tissu nouées, lettres écrites à la main',
    ],
  },
  {
    numero: 23,
    titre: 'Le musée privé',
    style: 'Art contemporain, galerie',
    terroir: 'une galerie blanche, un collectionneur, une sculpture au sol',
    matiere: 'plâtre, marbre, acier, verre, peinture fraîche',
    motif: 'l’espace vide autour de l’œuvre',
    lumiere: 'lumière muséale, zénithale, sans ombre visible',
    palette: { fond: '#EFEFEA', accent: '#111111' },
    coverSujet:
      'une sculpture contemporaine au sol dans une galerie vide, cimaise blanche, lumière zénithale',
    chapitres: [
      'deux personnes debout devant une même œuvre, vues de dos',
      'un bijou sculptural porté comme une pièce de musée, très gros plan',
      'un musée vide avant l’ouverture, parquet ciré, mains courantes',
      'une table composée comme une nature morte contemporaine',
      'une performance artistique en cours, corps en mouvement, silence',
      'des œuvres d’un autre continent accrochées ensemble, cartels',
      'une réserve de musée, œuvres emballées, fiches d’inventaire',
    ],
  },
  {
    numero: 24,
    titre: 'Menu printemps',
    style: 'Gastronomie végétale, nature morte',
    terroir: 'une cuisine de restaurant, un marché de primeur, un potager',
    matiere: 'asperges, fraises, herbes, terre cuite',
    motif: 'le produit à son meilleur moment, jamais transformé à l’excès',
    lumiere: 'lumière de fenêtre de cuisine, blanche et franche',
    palette: { fond: '#DDE3C9', accent: '#8C3B2E' },
    coverSujet:
      'une table de cuisine de printemps, asperges vertes, fraises, herbes fraîches, couteau posé',
    chapitres: [
      'quatre mains autour d’une pâte à tarte, farine sur les avant-bras',
      'un tablier de cuisine taché et des mains nouées dans un torchon',
      'un potager de restaurant sous serre, terreau et plants alignés',
      'un plat de printemps servi, assiettes de grès, vin nature',
      'un bar à cocktails d’herbes, mint, glace pilée, geste du barman',
      'un marché de primeurs au petit matin, cageots et voix',
      'des cahiers de recettes écrits à la main, taches de vin',
    ],
  },
  {
    numero: 25,
    titre: 'Mariages de mai',
    style: 'Folklore contemporain, culture populaire',
    terroir: 'un village, des prés en fleurs, un mai planté sur la place',
    matiere: 'rubans, houx, cuivre, muguet',
    motif: 'le présage : ce qu’on fait pour que l’année soit bonne',
    lumiere: 'lumière de mai, très longue, ciel d’orage au loin',
    palette: { fond: '#8CA36B', accent: '#B03B4E' },
    coverSujet:
      'un arbre de mai décoré de rubans sur la place d’un village, prés en fleurs, ciel d’orage au loin',
    chapitres: [
      'deux mains qui nouent un ruban autour d’une branche',
      'un brin de muguet à la boutonnière, bouton de veste en corne',
      'une place de village avec un mai planté, pavés, aucune foule',
      'une table de banquet de village, tréteaux, vin du pays',
      'une fanfare qui descend la rue, cuivres et tambours',
      'des croyances notées dans un carnet, signes et présages',
      'des vœux écrits accrochés à une branche, papiers au vent',
    ],
  },

  /* ——————————————————————————————— L'ÉTÉ ——————————————————————————————— */
  {
    numero: 26,
    titre: 'Testament corse',
    style: 'Méditerranée insulaire, documentaire',
    terroir: 'une crête de granit, une bergerie, la mer en contrebas',
    matiere: 'granit, maquis, cuir patiné, laine brute',
    motif: 'la pierre sèche : ce que les mains ont empilé sans ciment',
    lumiere: 'lumière dure de midi sur la pierre, mer aveuglante',
    palette: { fond: '#7A7B6E', accent: '#28556B' },
    coverSujet:
      'une crête de granit au-dessus de la mer, muret de pierres sèches, maquis qui monte dans la chaleur',
    chapitres: [
      'deux bergers qui se retrouvent à la porte de l’enclos, geste simple',
      'un manteau de laine brute et des mains qui ont travaillé, gros plan',
      'une bergerie de pierre sur la crête, mer en contrebas, aucune présence',
      'une table de bois sous la varangue, fromages, vin, pain de campagne',
      'trois voix qui chantent à la fin du repas, nuit qui tombe',
      'une procession de village, cierges et bannières au vent',
      'des photos punaisées et un carnet de famille écrit à la plume',
    ],
  },
  {
    numero: 27,
    titre: 'Le banquet bleu',
    style: 'Art de recevoir, nature morte',
    terroir: 'une table de plein air, un mur de chaux, des herbes hautes',
    matiere: 'lin brut, faïence bleue, verre, argenterie simple',
    motif: 'le bleu : chaque table de la semaine en porte un',
    lumiere: 'ombre d’un mur blanc, lumière réfléchie, aucune source directe',
    palette: { fond: '#3A5A7A', accent: '#EFEAD8' },
    coverSujet:
      'une grande table de lin brut à l’ombre d’un mur de chaux, faïence bleue, verres, herbes hautes autour',
    chapitres: [
      'deux mains qui posent une même assiette au centre de la table',
      'un chemisier de lin brut au col ouvert, cadre serré sur les épaules',
      'une cour de maison de pierre, table dressée dans l’ombre du mur',
      'des fruits, du pain et une carafe sur du lin bleu, nature morte',
      'des verres levés au-dessus de la table, mouvement arrêté',
      'une vaisselle de plusieurs pays sur une même table, mélange',
      'des menus écrits à la main, pliés, posés sur chaque assiette',
    ],
  },
  {
    numero: 28,
    titre: 'Cinéma d’été',
    style: 'Cinéma, lumière naturelle',
    terroir: 'une route de bord de mer, un drive-in, une villa des années 70',
    matiere: 'toile de transat, plastique jaune, chrome, sel',
    motif: 'le cadre : ce qu’on voit à travers une fenêtre ouverte',
    lumiere: 'soleil de fin d’après-midi, contre-jour assumés',
    palette: { fond: '#D97A2B', accent: '#25607A' },
    coverSujet:
      'une voiture américaine garée sous un écran de drive-in éteint, fin d’après-midi, côte en arrière-plan',
    chapitres: [
      'un couple dans une décapotable, vus de dos, cheveux au vent',
      'une robe imprimée des années 70, lunettes de soleil, gros plan',
      'une villa des années 70 au-dessus de la mer, volets fermés',
      'une glacière, des fruits coupés sur une table de terrasse',
      'une guinguette éclairée au bord de l’eau, piste de danse',
      'un tournage de rue, projecteurs et câbles en plein jour',
      'une caméra super 8 posée dans le sable, courroie usée',
    ],
  },
  {
    numero: 29,
    titre: 'Hot Jazz',
    style: 'Musique noire américaine, club',
    terroir: 'un club de 1959, un quartier de nuit, une scène en bois',
    matiere: 'cuivre, velours usé, bois de scène, whisky',
    motif: 'la sueur et le cuivre : ce que la musique fait au corps',
    lumiere: 'une seule poursuite jaune, noirs profonds',
    palette: { fond: '#3A2318', accent: '#D9A227' },
    coverSujet:
      'une trompette en cuivre posée sur une chaise de club vide, micro ancien, lumière jaune unique',
    chapitres: [
      'deux danseurs collés au bord de la scène, mouvement flou',
      'un costume de scène en velours, nœud papillon, gros plan',
      'une façade de club de nuit, enseigne au néon jaune',
      'un bar de club, verres épais, glace, main du barman',
      'un quartet en pleine nuit, cuivres et contrebasse',
      'un quartier de musique, portes ouvertes, sons qui se mélangent',
      'des pochettes de vinyles empilées, étiquettes écrites à la main',
    ],
  },
  {
    numero: 30,
    titre: 'Vacances à Capri',
    style: 'Dolce vita, luxe solaire',
    terroir: 'une terrasse au-dessus de la mer, un bateau, une limonade',
    matiere: 'toile de lin blanc, citron, majolique, laiton',
    motif: 'le blanc et le jaune, contre le bleu absolu',
    lumiere: 'lumière méditerranéenne de onze heures, ombres courtes',
    palette: { fond: '#EFE3C2', accent: '#1F6F8B' },
    coverSujet:
      'une terrasse de pierre au-dessus d’une mer bleue absolue, citrons, nappe blanche, aucune présence',
    chapitres: [
      'deux silhouettes allongées au bord de l’eau, vue de loin, ombrelle',
      'un chapeau de paille et un maillot blanc, gros plan, peau salée',
      'des escaliers taillés dans la falaise descendant à la mer',
      'des citrons, une majolique, un poisson grillé, pain et huile',
      'une fête sur une terrasse, guirlandes, verres et musique',
      'un port de pêche au petit matin, barques et voix',
      'un appareil photo argentique et des pellicules sur une serviette',
    ],
  },
  {
    numero: 31,
    titre: 'Désert Motel',
    style: 'Americana, cinéma indépendant',
    terroir: 'une route droite, un motel, une piscine vide',
    matiere: 'néon, tôle, sable, vinyle',
    motif: 'le néon qui grésille dans la nuit chaude',
    lumiere: 'coucher de soleil orange puis bleu de nuit, néons',
    palette: { fond: '#B4552A', accent: '#2B6E7A' },
    coverSujet:
      'un motel au bord d’une route droite au coucher du soleil, néon allumé, piscine vide, sable',
    chapitres: [
      'deux silhouettes qui marchent le long d’une route déserte, de dos',
      'une robe légère couverte de poussière, bottes, gros plan',
      'un canyon ou un désert vide, route sans fin, chaleur visible',
      'un dîner de motel, hamburger et tarte, banquette de vinyle',
      'un juke-box allumé dans une salle vide, lumières colorées',
      'une station-service la nuit, enseigne, employé seul',
      'un motel au petit matin, cartes postales écrites à la réception',
    ],
  },
  {
    numero: 32,
    titre: 'La grande table d’août',
    style: 'Gastronomie de village, reportage',
    terroir: 'une place d’été, des tréteaux, une fontaine',
    matiere: 'toile cirée, melon, rosé, verre épais',
    motif: 'la table trop longue : on est trop nombreux, et c’est bien',
    lumiere: 'lumière de dix-neuf heures, ombres longues sur le gravier',
    palette: { fond: '#C97D3A', accent: '#5B7A3A' },
    coverSujet:
      'une table trop longue dressée sur une place, nappes à motifs, melons coupés, ombres du soir',
    chapitres: [
      'des mains qui se passent un plat le long de la table, rire au loin',
      'un T-shirt de lin froissé et une nappe tachée, gros plan',
      'une place de village aux volets fermés, chaleur, aucune présence',
      'un melon entamé, du rosé, des verres épais, table de gravier',
      'une fête de village, sono, lumières, quelqu’un qui monte sur la table',
      'un producteur au marché, panier, main tendue avec des pièces',
      'des listes de courses écrites à la main, punaisées au mur',
    ],
  },
  {
    numero: 33,
    titre: 'Venise en août',
    style: 'Voyage, patrimoine, documentaire',
    terroir: 'les canaux, un palazzo, la lagune à l’aube',
    matiere: 'pierre d’Istrie, eau verte, verre de Murano, velours usé',
    motif: 'la lumière reflétée par l’eau sur les plafonds',
    lumiere: 'lumière réfléchie par l’eau, tremblante, dans les sous-plafonds',
    palette: { fond: '#4E6E6B', accent: '#8C2F39' },
    coverSujet:
      'une façade de palazzo vénitien tombant dans un canal calme à l’aube, eau verte, aucune gondole',
    chapitres: [
      'deux personnes qui se tiennent dans une barque, vues de dos',
      'un verre de Murano et un tissu de velours posés sur du marbre',
      'un campo vide avant les touristes, dalles polies par le temps',
      'des fruits de mer sur une table de pierre, verres de vin blanc',
      'un bal populaire sur une place, guirlandes entre les palazzi',
      'des archives de la lagune, registres et sceaux de cire',
      'des tirages argentiques posés à sécher sur une corde',
    ],
  },
  {
    numero: 34,
    titre: 'Zen d’été',
    style: 'Japon contemporain, épure',
    terroir: 'une maison de bois, un jardin sec, un tatami',
    matiere: 'cèdre clair, tatami, papier washi, pierre',
    motif: 'le vide comme matière : un objet, beaucoup d’air',
    lumiere: 'lumière tamisée par un shoji, très douce, presque grise',
    palette: { fond: '#D9D5C8', accent: '#3B4A44' },
    coverSujet:
      'une pièce de tatami vide, un seul vase de branches, lumière tamisée par un panneau de papier',
    chapitres: [
      'deux mains qui se tendent une tasse, geste lent, tatami au sol',
      'un kimono contemporain de lin sombre, pli parfait, ceinture nouée',
      'un jardin sec de gravier ratissé, une pierre, un mur de terre',
      'des mets d’été servis dans des bols, laque, baguettes posées',
      'un tambour taiko dans une cour, lumière du soir, mouvement',
      'des lanternes de papier allumées au bord d’une rivière',
      'des lettres pliées selon la tradition, papier washi, encre',
    ],
  },
  {
    numero: 35,
    titre: 'Oaxaca',
    style: 'Amérique latine, fête et culture',
    terroir: 'un carnaval, un marché, une église de pierre rose',
    matiere: 'papier découpé, tissage, terre cuite, argent',
    motif: 'le papier découpé et la couleur qui déborde',
    lumiere: 'lumière dure, couleurs saturées, ombres noires',
    palette: { fond: '#B23A48', accent: '#E0A458' },
    coverSujet:
      'une ruelle de pierre rose couverte de papier découpé multicolore, ciel bleu dur, aucune présence',
    chapitres: [
      'deux personnes qui dansent dans une foule, mains liées, mouvement',
      'un textile tissé main porté en châle, couleurs vives, gros plan',
      'des ruines de pierre sur une colline, agaves, ciel d’orage',
      'une table de fête mexicaine, mole, chocolat, terre cuite',
      'un orchestre de carnaval, papier découpé au-dessus des têtes',
      'une procession religieuse colorée, cierges et fleurs d’été',
      'des tissus pliés et des lettres d’une grand-mère, mots en espagnol',
    ],
  },
  {
    numero: 36,
    titre: 'Portraits d’été',
    style: 'Photographie analogique, studio plein air',
    terroir: 'un mur au soleil, un parasol, un sol de ciment chaud',
    matiere: 'argentique, ciment, coton blanc, sel',
    motif: 'l’ombre de l’objet sur le mur, à midi',
    lumiere: 'soleil direct de midi, ombre nette, aucune retouche',
    palette: { fond: '#E8D8BC', accent: '#1F1F1F' },
    coverSujet:
      'un mur au soleil avec l’ombre nette d’un parasol et d’une chaise, sol de ciment chaud, aucune personne',
    chapitres: [
      'deux corps allongés dans l’ombre d’un mur, vus de haut, mains proches',
      'un tissu de coton blanc porté en drapé, ombre portée sur la peau',
      'un escalier extérieur à midi, ombres géométriques, chaleur',
      'des tomates et du pain dans l’ombre, table de ciment, sel',
      'une radio qui joue dans une cour, ombre des haut-parleurs',
      'une fenêtre ouverte sur une rue d’été, rideau qui bouge',
      'un négatif 35 mm tenu devant la lumière du soleil',
    ],
  },
  {
    numero: 37,
    titre: 'La côte volcanique',
    style: 'Nature brute, paysage',
    terroir: 'une falaise de basalte, un océan noir, un vent constant',
    matiere: 'basalte, sel, lichen, écume',
    motif: 'l’arête noire contre l’écume blanche',
    lumiere: 'lumière dure tamisée par les embruns, contraste minéral',
    palette: { fond: '#26282B', accent: '#8FA3A6' },
    coverSujet:
      'une falaise de basalte plongeant dans un océan agité, écume blanche, lichen jaune sur la pierre',
    chapitres: [
      'deux silhouettes accrochées l’une à l’autre face au vent',
      'un vêtement de laine mouillé de sel, épaule et col, gros plan',
      'une côte noire au petit matin, brume d’embruns, aucune présence',
      'des coquillages et du pain sur une table de pierre, vent visible',
      'un feu allumé sur la plage, guitares, nuit noire sans lune',
      'des pêcheurs qui remontent leurs casiers, gestes précis',
      'un carnet de bord taché de sel, écritures serrées',
    ],
  },
  {
    numero: 38,
    titre: 'Septembre doré',
    style: 'Lumière d’arrière-saison, éditorial',
    terroir: 'un champ moissonné, une allée, un village fin septembre',
    matiere: 'chaume, lin é cru, verre soufflé, cuivre',
    motif: 'la lumière basse qui traverse tout, jusqu’au verre',
    lumiere: 'golden hour longue, poussière en suspension',
    palette: { fond: '#C98A3E', accent: '#3E4B3A' },
    coverSujet:
      'un champ moissonné à la golden hour, poussière dans la lumière, une seule chaise de bois, aucune présence',
    chapitres: [
      'deux personnes qui marchent sur un chemin de chaume, mains qui se cherchent',
      'un manteau de lin écru, ceinture de cuir, lumière rasante sur l’épaule',
      'une allée de tilleuls en fin de journée, ombres très longues',
      'des figues, du miel et du vin blanc, table sous les arbres',
      'une fête en plein air à la nuit tombante, guirlandes et poussière',
      'une fête de village de septembre, lampions et musique',
      'un album qu’on vient de terminer, tirages encore sur la table',
    ],
  },

  /* —————————————————————————————— L'AUTOMNE —————————————————————————————— */
  {
    numero: 39,
    titre: 'Forêt noire',
    style: 'Nature sombre, rituel',
    terroir: 'une sapinière, la brume, un sous-bois de champignons',
    matiere: 'mousse, écorce, laine épaisse, fer noir',
    motif: 'l’arbre qui tient la lumière : tronc, branche, canopée',
    lumiere: 'lumière filtrée par la canopée, brume basse',
    palette: { fond: '#25301F', accent: '#BFC7A6' },
    coverSujet:
      'une sapinière dans la brume du matin, mousse et fougères, un rai de lumière filtré, aucune présence',
    chapitres: [
      'deux personnes qui se tiennent par la main dans un sous-bois brumeux',
      'une cape de laine épaisse et des bottes de cuir, gros plan',
      'des troncs alignés dans la brume, perspective infinie',
      'des champignons et du pain noir sur une table de bois brut',
      'des lanternes suspendues aux branches, cercle de lumière',
      'un rituel forestier, gestes lents, couronne de fougères',
      'des empreintes et un carnet de relevés dans la mousse',
    ],
  },
  {
    numero: 40,
    titre: 'La cité brutaliste',
    style: 'Architecture, graphisme urbain',
    terroir: 'un ensemble de béton, une dalle, une place minérale',
    matiere: 'béton brut, coffrage, acier, verre fumé',
    motif: 'l’ombre portée du bâtiment sur lui-même',
    lumiere: 'lumière dure découpant les arêtes, ciel blanc',
    palette: { fond: '#6E6E6A', accent: '#1E1E1E' },
    coverSujet:
      'un ensemble de béton brut vu d’en dessous, arêtes franches, ciel blanc, une seule fenêtre éclairée',
    chapitres: [
      'deux personnes assises sur une dalle de béton, vues de loin',
      'un manteau structuré, épaules nettes, contre un mur de béton',
      'une cage d’escalier brutaliste, béton et lumière zénithale',
      'une table de cantine en béton ciré, assiettes mates, eau',
      'une piste de danse sur une dalle, lumières blanches et son',
      'un quartier entier de béton, symétrie, vie qui s’y installe',
      'des plans d’architecte annotés, maquette de carton',
    ],
  },
  {
    numero: 41,
    titre: 'Rentrée des classes',
    style: 'Documentaire rétro, nostalgie',
    terroir: 'une école de village, un cartable, un encrier',
    matiere: 'bois verni, toile cirée, papier réglé, encre violette',
    motif: 'l’écriture manuscrite d’enfant, appliquée',
    lumiere: 'lumière d’octobre par les vitres hautes d’une classe',
    palette: { fond: '#8A6A4A', accent: '#2E4A6B' },
    coverSujet:
      'une salle de classe ancienne vide, pupitres de bois alignés, cartable posé, lumière d’octobre',
    chapitres: [
      'deux enfants qui se tiennent la main dans une cour d’école',
      'un uniforme repassé, chaussures cirées, tablier de toile',
      'une cour d’école déserte, marquage au sol, platane',
      'un goûter de rentrée, pain et chocolat, toile cirée',
      'une chorale d’école qui répète, pupitres debout',
      'une carte du monde punaisée, punaises de couleur',
      'des cahiers d’écolier remplis à l’encre violette',
    ],
  },
  {
    numero: 42,
    titre: 'Le cinéma des années 70',
    style: 'Cinéma, grain et pellicule',
    terroir: 'un motel de cinéma, un polar de province, une pellicule Kodachrome',
    matiere: 'denim, cuir, laine, pellicule chaude',
    motif: 'le grain : l’image qui garde la trace du temps',
    lumiere: 'lumière chaude et hautes lumières qui brûlent légèrement',
    palette: { fond: '#7A5A34', accent: '#3D5A5A' },
    coverSujet:
      'une voiture des années 70 garée devant un motel de province, lumière chaude de fin de journée, grain visible',
    chapitres: [
      'deux personnes qui se regardent dans une voiture, hors champ inversé',
      'un col de chemise ouvert, chaîne fine, gros plan sur le denim',
      'une route de province, panneaux délavés, chaleur au sol',
      'des frites et des sodas sur un capot de voiture, pique-nique',
      'un jukebox de bar, bières, néons et fumée',
      'une fête foraine de province, lumières et odeurs',
      'des diapositives projetées sur un drap blanc',
    ],
  },
  {
    numero: 43,
    titre: 'Fashion week',
    style: 'Mode contemporaine, défilé',
    terroir: 'un studio de défilé, un backstage, une avenue',
    matiere: 'soie, cuir, maille fine, métal',
    motif: 'le vêtement en mouvement : le tissu qui se déplace',
    lumiere: 'lumière de studio, contraste maîtrisé, blancs nets',
    palette: { fond: '#1C1C22', accent: '#C4623A' },
    coverSujet:
      'un podium de défilé vide avant l’ouverture, néons blancs, chaises alignées, aucune présence',
    chapitres: [
      'deux personnes dans les coulisses, front contre front, hors pose',
      'une pièce de couture portée, drapé spectaculaire, visage hors cadre',
      'une avenue pavée au petit matin, façades haussmanniennes, vide',
      'un plateau de traiteur de défilé, verres et petits fours',
      'un DJ et une piste improvisée après le défilé, nuit',
      'des ateliers de mode de plusieurs pays, mains et machines',
      'des moodboards et des tirages punaisés dans un studio',
    ],
  },
  {
    numero: 44,
    titre: 'Toscane',
    style: 'Italie, terroir et lumière dorée',
    terroir: 'une colline de cyprès, une villa, un pressoir',
    matiere: 'pierre ocre, terre cuite, lin, huile d’olive',
    motif: 'la ligne des cyprès et la lumière qui descend',
    lumiere: 'lumière dorée de fin d’après-midi sur la pierre ocre',
    palette: { fond: '#C0854A', accent: '#4E5B3A' },
    coverSujet:
      'une colline de cyprès derrière une villa de pierre ocre, vigne et lumière dorée, aucune présence',
    chapitres: [
      'deux personnes qui se tiennent devant une table longue, vues de dos',
      'une robe de lin couleur d’huile, plis, broderie discrète',
      'une allée de cyprès descendant vers une maison de pierre',
      'une table sous la pergola, pâtes fraîches, huile, vin rouge',
      'une fête dans une cour de ferme, guirlandes et musique',
      'un pressoir et des mains de vigneron, geste ancien',
      'des photographies de famille dans un tiroir de buffet',
    ],
  },
  {
    numero: 45,
    titre: 'L’atelier du photographe',
    style: 'Studio, chambre noire, art',
    terroir: 'un studio, une chambre noire, un laboratoire de tirage',
    matiere: 'baryté, chimie, acier, toile de fond',
    motif: 'la lumière rouge de la chambre noire',
    lumiere: 'lampe rouge et lumière de studio, mélange de sources',
    palette: { fond: '#4A1F1F', accent: '#D9CBB2' },
    coverSujet:
      'une chambre noire en pleine activité, bacs de chimie, tirages dans l’eau, lumière rouge, aucune présence',
    chapitres: [
      'deux personnes devant un même tirage, têtes penchées',
      'un vêtement blanc sur toile de fond, pince à linge, gros plan',
      'un studio vide, toile de fond roulée, lumière de fenêtre',
      'une table de laboratoire, tasses, bouteilles de chimie',
      'un flash de studio qui part près d’une danse, lumière dure',
      'des tirages de plusieurs pays posés à sécher sur un fil',
      'une planche de négatifs tenue devant la lumière rouge',
    ],
  },
  {
    numero: 46,
    titre: 'Maroc',
    style: 'Monde, artisanat et couleur',
    terroir: 'une médina, un atelier de tapis, une terrasse ocre',
    matiere: 'terre cuite, tapis noués, cuivre, henné',
    motif: 'le motif géométrique répété, à l’infini',
    lumiere: 'lumière dure et ombre fraîche, bleu profond au-dessus',
    palette: { fond: '#B4552A', accent: '#1E5A6B' },
    coverSujet:
      'une terrasse ocre au-dessus d’une médina, tapis étendus, lumière dure, ombres nettes, aucune présence',
    chapitres: [
      'deux mains qui se nouent autour d’un poignet au henné',
      'un caftan de soie, broderies main, posé sur un tapis noué',
      'des ruelles de médina, murs ocre, porte ancienne cloutée',
      'un plateau de thé et d’amandes, cuivre martelé, pain',
      'des percussions gnawa, foule en cercle, nuit chaude',
      'un atelier d’artisanat, mains qui tissent, couleurs vives',
      'des lettres écrites en arabe, enveloppes timbrées',
    ],
  },
  {
    numero: 47,
    titre: 'Vins & chandelles',
    style: 'Gastronomie fine, cave',
    terroir: 'une cave voûtée, une table basse, des bouteilles numérotées',
    matiere: 'verre soufflé, cire, chêne, pierre humide',
    motif: 'la bougie qui tient la nuit de bout en bout',
    lumiere: 'bougies uniquement, clair-obscur sur la pierre',
    palette: { fond: '#2B2119', accent: '#D9B26A' },
    coverSujet:
      'une cave voûtée éclairée à la bougie, bouteilles alignées et crayeuses, table de pierre, aucune présence',
    chapitres: [
      'deux verres levés devant une bougie, mains en amorce',
      'un velours sombre porté dans la pénombre, reflet doré',
      'une cave voûtée vide, poussière dans la lumière d’une bougie',
      'une table de dégustation, fromages, pain, verres numérotés',
      'un accordéon et un violon dans une cave, concert privé',
      'des étiquettes de vins de plusieurs pays alignées',
      'des carnets de dégustation remplis à la plume',
    ],
  },
  {
    numero: 48,
    titre: 'Lagos néon',
    style: 'Afrique contemporaine, pop',
    terroir: 'une ville qui ne dort pas, un atelier de couture, un rooftop',
    matiere: 'wax, sequins, néon, plastique coloré',
    motif: 'le wax à grandes écailles, porté en volume',
    lumiere: 'néons et lumière chaude, nuit saturée',
    palette: { fond: '#1F3A2E', accent: '#F2994A' },
    coverSujet:
      'un rooftop de nuit au-dessus d’une ville africaine, néons orange et verts, tissus wax tendus, aucune présence',
    chapitres: [
      'deux personnes qui rient dans une rue animée, corps en mouvement',
      'un wax à grandes écailles, taille structurée, cou et mains',
      'une ville vue de haut la nuit, enseignes, circulation lumineuse',
      'un plateau de plats épicés, bananes plantain, table colorée',
      'un concert afrobeats, scène et foule en fusion',
      'un atelier de couture, machines, tissus empilés, mains rapides',
      'des cartes postales et des photographies de studio, années 70',
    ],
  },
  {
    numero: 49,
    titre: 'Le château aujourd’hui',
    style: 'Patrimoine moderne, architecture',
    terroir: 'un château revisité, une verrière de corten, une allée de tilleuls',
    matiere: 'pierre blonde, corten, verre, gazon',
    motif: 'l’ancien et le contemporain dans le même cadre',
    lumiere: 'lumière rasante sur la pierre, reflets sur le verre',
    palette: { fond: '#A8A69A', accent: '#47614A' },
    coverSujet:
      'un château de pierre blonde avec une extension de verre et d’acier, allée de tilleuls, lumière rasante',
    chapitres: [
      'deux personnes dans la cour pavée, vues de loin, mains liées',
      'un costume contemporain à côté d’un miroir ancien, reflets',
      'une verrière de corten posée contre un mur de pierre, vide',
      'une table dressée dans une orangerie, verres, fruits du jardin',
      'une fête sous les tilleuls, guirlandes entre les troncs',
      'des archives du domaine, plans anciens et clés de fer',
      'une galerie de portraits et de tirages contemporains mêlés',
    ],
  },
  {
    numero: 50,
    titre: 'Souvenirs de la maison',
    style: 'Archives, mémoire, éditorial intime',
    terroir: 'un grenier, une boîte de famille, un tiroir de secrétaire',
    matiere: 'papier jauni, cuir, étain, tissu fané',
    motif: 'la boîte ouverte et ce qui en sort, un objet à la fois',
    lumiere: 'lumière de grenier, poussière visible dans un rai',
    palette: { fond: '#6B5B45', accent: '#C9A227' },
    coverSujet:
      'un grenier calme, une boîte ancienne ouverte, tirages, lettres et rubans, poussière dans un rai de lumière',
    chapitres: [
      'deux mains qui se passent un objet de famille, geste suspendu',
      'un bijou ancien transmis, patine visible, gros plan sur la main',
      'un grenier sous les toits, malles et housses, lumière basse',
      'une recette de famille recopiée, tache de vin, gâteau',
      'un disque de famille passé sur un tourne-disque ancien',
      'des objets rapportés de plusieurs pays posés ensemble',
      'des albums numérotés, tirages annotés, élastique craquelé',
    ],
  },
  {
    numero: 51,
    titre: 'Avant l’hiver',
    style: 'Fin de saison, éditorial',
    terroir: 'un parc qui se vide, des manteaux, la dernière terrasse',
    matiere: 'laine feutrée, cuir, feuilles mortes, givre naissant',
    motif: 'les dernières feuilles et les dernières lumières',
    lumiere: 'lumière basse et pâle de novembre, brume légère',
    palette: { fond: '#5B5A52', accent: '#B8863B' },
    coverSujet:
      'un parc à la lumière pâle de novembre, dernières feuilles sur un banc de pierre, brume légère, aucune présence',
    chapitres: [
      'deux personnes qui se serrent dans un manteau trop grand',
      'un manteau de laine feutrée et des gants de cuir, gros plan',
      'une allée de parc au petit matin, feuilles mouillées, brume',
      'un dernier déjeuner en terrasse, soupe, vin rouge, plaids',
      'une fête de fin de saison dans une salle chauffée, lumières',
      'un marché d’automne, courges, champignons, laine',
      'un album de l’année qu’on referme, tirages empilés',
    ],
  },
  {
    numero: 52,
    titre: 'La table d’hiver',
    style: 'Gastronomie rurale, braises',
    terroir: 'une cuisine de ferme, un four à pain, une table de Noël',
    matiere: 'fonte, pain, racines, vin chaud',
    motif: 'la braise : ce qui cuit lentement, longtemps',
    lumiere: 'lumière du four ouvert et bougies de table',
    palette: { fond: '#7A3B24', accent: '#EFD9A8' },
    coverSujet:
      'une cuisine de ferme en hiver, four à pain ouvert, braises, légumes racines et pain sur la table, aucune présence',
    chapitres: [
      'des mains qui se réchauffent autour d’un plat brûlant',
      'une maille épaisse et un tablier de toile devant les braises',
      'une ferme sous la neige, cheminée qui fume, volets fermés',
      'une table d’hiver, pain, vin chaud, bougies, vaisselle simple',
      'une veillée, chants et guitares, bougies par dizaines',
      'des recettes de village recopiées, écritures anciennes',
      'des photographies de Noël classées par année',
    ],
  },

  /* ————————————————————————— LES DEUX JOURS DE TROP ————————————————————————— */
  {
    numero: 53,
    titre: 'Le jour de trop',
    style: 'Surréalisme, conceptuel',
    terroir: 'le 365ᵉ jour : celui qui n’était pas prévu',
    matiere: 'horloges, papiers, glace, encre',
    motif: 'le temps qui dépasse : une mesure impossible à tenir',
    lumiere: 'lumière froide d’un jour suspendu, sans heure',
    palette: { fond: '#1B1B1F', accent: '#E8E4DA' },
    coverSujet:
      'une pièce vide remplie d’horloges arrêtées à la même heure, neige légère dans la lumière, aucune présence',
    chapitres: [
      'deux personnes qui se rencontrent un jour qui n’existait pas, hors champ',
      'une montre ancienne ouverte, mécanisme visible, gros plan',
      'une ville sous la neige à une heure impossible, rues vides',
      'un repas dressé pour une date qui n’existe pas, bougies seules',
      'une piste de danse vide avec la musique qui continue',
      'des calendriers de plusieurs cultures, dates qui ne coïncident pas',
      'une lettre datée du 32 décembre, écriture appliquée',
    ],
  },
  {
    numero: 54,
    titre: 'Le jour qui n’existe pas',
    style: 'Conceptuel, art et science',
    terroir: 'le 29 février : tous les quatre ans, une journée de plus',
    matiere: 'verre, eau, papier, reflets',
    motif: 'le reflet : deux fois la même image, jamais tout à fait',
    lumiere: 'lumière réfléchie, double source, ombres symétriques',
    palette: { fond: '#3A2A44', accent: '#9FD0E8' },
    coverSujet:
      'un plan d’eau parfaitement calme reflétant un ciel d’hiver, un seul objet posé au bord, aucune présence',
    chapitres: [
      'deux personnes séparées par un reflet, à la même place',
      'un voile de lin blanc dans un courant d’air, transparence',
      'un bâtiment symétrique reflété par un bassin, aucune présence',
      'une table dressée pour deux, dans une lumière double',
      'une danse filmée et projetée en même temps, deux mouvements',
      'des calendriers julien et grégorien côte à côte, différence',
      'deux tirages identiques, l’un inversé, posés côte à côte',
    ],
  },
];

/** La direction d'un numéro (1 à 54). Le rang, jamais le numéro, sert d'index. */
export function directionDuNumero(numero: number): DirectionDuMagazine {
  return DIRECTIONS[numero - 1] ?? DIRECTIONS[0]!;
}

/** Vrai quand les 54 directions sont écrites, dans l'ordre, sans trou. */
export const DIRECTIONS_COMPLETES =
  DIRECTIONS.length === 54 && DIRECTIONS.every((d, i) => d.numero === i + 1);
