/**
 * LES 364 PRÉNOMS DE L'ANNÉE — LE CALENDRIER, JOUR PAR JOUR
 *
 * Un jour, un prénom. C'est le calendrier français — celui des saints et des
 * fêtes — et il sert ici à deux choses :
 *
 * 1. **les couvertures** : onze jours sur douze portent un prénom, et le
 *    magazine du jour s'appelle par lui. **364 couvertures nommées** : les
 *    364 jours qui restent quand on a retiré les deux **jokers** du calendrier
 *    (le 31 décembre et le 29 février) — les mêmes deux jokers que le jeu de 54
 *    (n° 53 « le jour de trop », n° 54 « le jour bissextile ») ;
 * 2. **les visages** : ces prénoms sont les **personnages** du produit — des
 *    exemples à nous, qui rendent le magazine habité. On ne prétend pas qu'ils
 *    sont des personnes : ce sont les noms du calendrier, comme les cartes sont
 *    les semaines.
 *
 * **La source, et sa limite.** Le calendrier vient d'un **jeu ouvert** (« Les
 * saints et les fêtes du calendrier », repris du dépôt `theofidry/ephemeris` en
 * JSON) et il a été relu : orthographes, accents, et les quelques jours où la
 * source donnait une fête mobile (les Cendres, les solstices) remplacés par le
 * prénom du jour. La référence française reste **Nominis** (Conférence des
 * évêques de France) : deux calendriers ne donnent pas exactement la même liste,
 * et le nôtre s'en approche sans en être la copie. Voir `docs/noyau-reseau.md`
 * §40.
 */

export type Genre = 'saint' | 'sainte' | 'fete';

export interface JourNomme {
  /** Le mois, 1 à 12. */
  mois: number;
  /** Le jour du mois. */
  jour: number;
  /** Le prénom (ou le nom de la fête). */
  nom: string;
  genre: Genre;
  /** Son rang parmi les 364 couvertures nommées, de 1 à 364. */
  ordinal: number;
}

/** `[mois, jour, prénom, genre]` — les 364 couvertures nommées. */
const TABLE: Array<[number, number, string, Genre]> = [
  [ 1,  1, 'Jour de l’An', 'fete'],
  [ 1,  2, 'Basile', 'saint'],
  [ 1,  3, 'Geneviève', 'sainte'],
  [ 1,  4, 'Odilon', 'saint'],
  [ 1,  5, 'Édouard', 'saint'],
  [ 1,  6, 'Mélaine', 'saint'],
  [ 1,  7, 'Raymond', 'saint'],
  [ 1,  8, 'Lucien', 'saint'],
  [ 1,  9, 'Alix', 'sainte'],
  [ 1, 10, 'Guillaume', 'saint'],
  [ 1, 11, 'Pauline', 'sainte'],
  [ 1, 12, 'Tatiana', 'sainte'],
  [ 1, 13, 'Yvette', 'sainte'],
  [ 1, 14, 'Nina', 'sainte'],
  [ 1, 15, 'Rémi', 'saint'],
  [ 1, 16, 'Marcel', 'saint'],
  [ 1, 17, 'Roseline', 'sainte'],
  [ 1, 18, 'Prisca', 'sainte'],
  [ 1, 19, 'Marius', 'saint'],
  [ 1, 20, 'Sébastien', 'saint'],
  [ 1, 21, 'Agnès', 'sainte'],
  [ 1, 22, 'Vincent', 'saint'],
  [ 1, 23, 'Barnard', 'saint'],
  [ 1, 24, 'François de Sales', 'saint'],
  [ 1, 25, 'La Conversion de Paul', 'fete'],
  [ 1, 26, 'Paule', 'sainte'],
  [ 1, 27, 'Angèle', 'sainte'],
  [ 1, 28, 'Thomas d’Aquin', 'saint'],
  [ 1, 29, 'Gildas', 'saint'],
  [ 1, 30, 'Martine', 'sainte'],
  [ 1, 31, 'Marcelle', 'sainte'],
  [ 2,  1, 'Ella', 'sainte'],
  [ 2,  2, 'La Présentation du Seigneur', 'fete'],
  [ 2,  3, 'Blaise', 'saint'],
  [ 2,  4, 'Véronique', 'sainte'],
  [ 2,  5, 'Agathe', 'sainte'],
  [ 2,  6, 'Gaston', 'saint'],
  [ 2,  7, 'Eugénie', 'sainte'],
  [ 2,  8, 'Jacqueline', 'sainte'],
  [ 2,  9, 'Apolline', 'sainte'],
  [ 2, 10, 'Arnaud', 'saint'],
  [ 2, 11, 'Notre-Dame de Lourdes', 'fete'],
  [ 2, 12, 'Félix', 'saint'],
  [ 2, 13, 'Béatrice', 'sainte'],
  [ 2, 14, 'Valentin', 'saint'],
  [ 2, 15, 'Claude', 'saint'],
  [ 2, 16, 'Julienne', 'sainte'],
  [ 2, 17, 'Alexis', 'saint'],
  [ 2, 18, 'Bernadette', 'sainte'],
  [ 2, 19, 'Gabin', 'saint'],
  [ 2, 20, 'Aimée', 'sainte'],
  [ 2, 21, 'Damien', 'saint'],
  [ 2, 22, 'Isabelle', 'sainte'],
  [ 2, 23, 'Lazare', 'saint'],
  [ 2, 24, 'Modeste', 'sainte'],
  [ 2, 25, 'Roméo', 'saint'],
  [ 2, 26, 'Nestor', 'saint'],
  [ 2, 27, 'Honorine', 'sainte'],
  [ 2, 28, 'Romain', 'saint'],
  [ 3,  1, 'Aubin', 'saint'],
  [ 3,  2, 'Charles le Bon', 'saint'],
  [ 3,  3, 'Guénolé', 'saint'],
  [ 3,  4, 'Casimir', 'saint'],
  [ 3,  5, 'Olive', 'sainte'],
  [ 3,  6, 'Colette', 'sainte'],
  [ 3,  7, 'Félicité', 'sainte'],
  [ 3,  8, 'Jean de Dieu', 'saint'],
  [ 3,  9, 'Françoise', 'sainte'],
  [ 3, 10, 'Vivien', 'saint'],
  [ 3, 11, 'Rosine', 'sainte'],
  [ 3, 12, 'Justine', 'sainte'],
  [ 3, 13, 'Rodrigue', 'saint'],
  [ 3, 14, 'Mathilde', 'sainte'],
  [ 3, 15, 'Louise', 'sainte'],
  [ 3, 16, 'Bénédicte', 'sainte'],
  [ 3, 17, 'Patrice', 'saint'],
  [ 3, 18, 'Cyrille', 'saint'],
  [ 3, 19, 'Joseph', 'saint'],
  [ 3, 20, 'Herbert', 'saint'],
  [ 3, 21, 'Clémence', 'sainte'],
  [ 3, 22, 'Léa', 'sainte'],
  [ 3, 23, 'Victorien', 'saint'],
  [ 3, 24, 'Karine', 'sainte'],
  [ 3, 25, 'L’Annonciation', 'fete'],
  [ 3, 26, 'Larissa', 'sainte'],
  [ 3, 27, 'Habib', 'saint'],
  [ 3, 28, 'Gontran', 'saint'],
  [ 3, 29, 'Gwladys', 'sainte'],
  [ 3, 30, 'Amédée', 'saint'],
  [ 3, 31, 'Benjamin', 'saint'],
  [ 4,  1, 'Hugues', 'saint'],
  [ 4,  2, 'Sandrine', 'sainte'],
  [ 4,  3, 'Richard', 'saint'],
  [ 4,  4, 'Isidore', 'saint'],
  [ 4,  5, 'Irène', 'sainte'],
  [ 4,  6, 'Marcellin', 'saint'],
  [ 4,  7, 'Jean-Baptiste de la Salle', 'saint'],
  [ 4,  8, 'Julie', 'sainte'],
  [ 4,  9, 'Gautier', 'saint'],
  [ 4, 10, 'Fulbert', 'saint'],
  [ 4, 11, 'Stanislas', 'saint'],
  [ 4, 12, 'Jules', 'saint'],
  [ 4, 13, 'Ida', 'sainte'],
  [ 4, 14, 'Maxime', 'saint'],
  [ 4, 15, 'Paterne', 'saint'],
  [ 4, 16, 'Benoît-Joseph', 'saint'],
  [ 4, 17, 'Anicet', 'saint'],
  [ 4, 18, 'Parfait', 'saint'],
  [ 4, 19, 'Emma', 'sainte'],
  [ 4, 20, 'Odette', 'sainte'],
  [ 4, 21, 'Anselme', 'saint'],
  [ 4, 22, 'Alexandre', 'saint'],
  [ 4, 23, 'Georges', 'saint'],
  [ 4, 24, 'Fidèle', 'saint'],
  [ 4, 25, 'Marc', 'saint'],
  [ 4, 26, 'Alida', 'sainte'],
  [ 4, 27, 'Zita', 'sainte'],
  [ 4, 28, 'Valérie', 'sainte'],
  [ 4, 29, 'Catherine de Sienne', 'sainte'],
  [ 4, 30, 'Robert', 'saint'],
  [ 5,  1, 'La Fête du travail', 'fete'],
  [ 5,  2, 'Boris', 'saint'],
  [ 5,  3, 'Philippe', 'saint'],
  [ 5,  4, 'Sylvain', 'saint'],
  [ 5,  5, 'Judith', 'sainte'],
  [ 5,  6, 'Prudence', 'sainte'],
  [ 5,  7, 'Gisèle', 'sainte'],
  [ 5,  8, 'L’Armistice de 1945', 'fete'],
  [ 5,  9, 'Pacôme', 'saint'],
  [ 5, 10, 'Solange', 'sainte'],
  [ 5, 11, 'Estelle', 'sainte'],
  [ 5, 12, 'Achille', 'saint'],
  [ 5, 13, 'Rolande', 'sainte'],
  [ 5, 14, 'Matthias', 'saint'],
  [ 5, 15, 'Denise', 'sainte'],
  [ 5, 16, 'Honoré', 'saint'],
  [ 5, 17, 'Pascal', 'saint'],
  [ 5, 18, 'Éric', 'saint'],
  [ 5, 19, 'Yves', 'saint'],
  [ 5, 20, 'Bernardin', 'saint'],
  [ 5, 21, 'Constantin', 'saint'],
  [ 5, 22, 'Émile', 'saint'],
  [ 5, 23, 'Didier', 'saint'],
  [ 5, 24, 'Donatien', 'saint'],
  [ 5, 25, 'Sophie', 'sainte'],
  [ 5, 26, 'Bérenger', 'saint'],
  [ 5, 27, 'Augustin', 'saint'],
  [ 5, 28, 'Germain', 'saint'],
  [ 5, 29, 'Aymar', 'saint'],
  [ 5, 30, 'Ferdinand', 'saint'],
  [ 5, 31, 'Perrine', 'sainte'],
  [ 6,  1, 'Justin', 'saint'],
  [ 6,  2, 'Blandine', 'sainte'],
  [ 6,  3, 'Kévin', 'saint'],
  [ 6,  4, 'Clotilde', 'sainte'],
  [ 6,  5, 'Igor', 'saint'],
  [ 6,  6, 'Norbert', 'saint'],
  [ 6,  7, 'Gilbert', 'saint'],
  [ 6,  8, 'Médard', 'saint'],
  [ 6,  9, 'Diane', 'sainte'],
  [ 6, 10, 'Landry', 'saint'],
  [ 6, 11, 'Barnabé', 'saint'],
  [ 6, 12, 'Guy', 'saint'],
  [ 6, 13, 'Antoine de Padoue', 'saint'],
  [ 6, 14, 'Élisée', 'saint'],
  [ 6, 15, 'Germaine', 'sainte'],
  [ 6, 16, 'Jean-François Régis', 'saint'],
  [ 6, 17, 'Hervé', 'saint'],
  [ 6, 18, 'Léonce', 'saint'],
  [ 6, 19, 'Romuald', 'saint'],
  [ 6, 20, 'Silvère', 'saint'],
  [ 6, 21, 'Rodolphe', 'saint'],
  [ 6, 22, 'Alban', 'saint'],
  [ 6, 23, 'Audrey', 'sainte'],
  [ 6, 24, 'Jean-Baptiste', 'saint'],
  [ 6, 25, 'Prosper', 'saint'],
  [ 6, 26, 'Anthelme', 'saint'],
  [ 6, 27, 'Fernand', 'saint'],
  [ 6, 28, 'Irénée', 'saint'],
  [ 6, 29, 'Pierre', 'saint'],
  [ 6, 30, 'Martial', 'saint'],
  [ 7,  1, 'Thierry', 'saint'],
  [ 7,  2, 'Martinien', 'saint'],
  [ 7,  3, 'Thomas', 'saint'],
  [ 7,  4, 'Florent', 'saint'],
  [ 7,  5, 'Antoine', 'saint'],
  [ 7,  6, 'Mariette', 'sainte'],
  [ 7,  7, 'Raoul', 'saint'],
  [ 7,  8, 'Thibault', 'saint'],
  [ 7,  9, 'Amandine', 'sainte'],
  [ 7, 10, 'Ulrich', 'saint'],
  [ 7, 11, 'Benoît', 'saint'],
  [ 7, 12, 'Olivier', 'saint'],
  [ 7, 13, 'Henri', 'saint'],
  [ 7, 14, 'La Fête nationale', 'fete'],
  [ 7, 15, 'Donald', 'saint'],
  [ 7, 16, 'Notre-Dame du Mont-Carmel', 'fete'],
  [ 7, 17, 'Charlotte', 'sainte'],
  [ 7, 18, 'Frédéric', 'saint'],
  [ 7, 19, 'Arsène', 'saint'],
  [ 7, 20, 'Marina', 'sainte'],
  [ 7, 21, 'Victor', 'saint'],
  [ 7, 22, 'Marie-Madeleine', 'sainte'],
  [ 7, 23, 'Brigitte', 'sainte'],
  [ 7, 24, 'Christine', 'sainte'],
  [ 7, 25, 'Jacques', 'saint'],
  [ 7, 26, 'Anne', 'sainte'],
  [ 7, 27, 'Nathalie', 'sainte'],
  [ 7, 28, 'Samson', 'saint'],
  [ 7, 29, 'Marthe', 'sainte'],
  [ 7, 30, 'Juliette', 'sainte'],
  [ 7, 31, 'Ignace de Loyola', 'saint'],
  [ 8,  1, 'Alphonse', 'saint'],
  [ 8,  2, 'Julien Eymard', 'saint'],
  [ 8,  3, 'Lydie', 'sainte'],
  [ 8,  4, 'Jean-Marie Vianney', 'saint'],
  [ 8,  5, 'Abel', 'saint'],
  [ 8,  6, 'La Transfiguration', 'fete'],
  [ 8,  7, 'Gaétan', 'saint'],
  [ 8,  8, 'Dominique', 'saint'],
  [ 8,  9, 'Amour', 'saint'],
  [ 8, 10, 'Laurent', 'saint'],
  [ 8, 11, 'Claire', 'sainte'],
  [ 8, 12, 'Clarisse', 'sainte'],
  [ 8, 13, 'Hippolyte', 'saint'],
  [ 8, 14, 'Évrard', 'saint'],
  [ 8, 15, 'L’Assomption', 'fete'],
  [ 8, 16, 'Armel', 'saint'],
  [ 8, 17, 'Hyacinthe', 'saint'],
  [ 8, 18, 'Hélène', 'sainte'],
  [ 8, 19, 'Jean-Eudes', 'saint'],
  [ 8, 20, 'Bernard', 'saint'],
  [ 8, 21, 'Christophe', 'saint'],
  [ 8, 22, 'Fabrice', 'saint'],
  [ 8, 23, 'Rose de Lima', 'sainte'],
  [ 8, 24, 'Barthélemy', 'saint'],
  [ 8, 25, 'Louis', 'saint'],
  [ 8, 26, 'Natacha', 'sainte'],
  [ 8, 27, 'Monique', 'sainte'],
  [ 8, 28, 'Augustin', 'saint'],
  [ 8, 29, 'Sabine', 'sainte'],
  [ 8, 30, 'Fiacre', 'saint'],
  [ 8, 31, 'Aristide', 'saint'],
  [ 9,  1, 'Gilles', 'saint'],
  [ 9,  2, 'Ingrid', 'sainte'],
  [ 9,  3, 'Grégoire', 'saint'],
  [ 9,  4, 'Rosalie', 'sainte'],
  [ 9,  5, 'Raïssa', 'sainte'],
  [ 9,  6, 'Bertrand', 'saint'],
  [ 9,  7, 'Reine', 'sainte'],
  [ 9,  8, 'La Nativité de la Vierge', 'fete'],
  [ 9,  9, 'Alain', 'saint'],
  [ 9, 10, 'Inès', 'sainte'],
  [ 9, 11, 'Adelphe', 'saint'],
  [ 9, 12, 'Apollinaire', 'saint'],
  [ 9, 13, 'Aimé', 'saint'],
  [ 9, 14, 'La Croix glorieuse', 'fete'],
  [ 9, 15, 'Roland', 'saint'],
  [ 9, 16, 'Edith', 'sainte'],
  [ 9, 17, 'Renaud', 'saint'],
  [ 9, 18, 'Nadège', 'sainte'],
  [ 9, 19, 'Émilie', 'sainte'],
  [ 9, 20, 'Davy', 'saint'],
  [ 9, 21, 'Matthieu', 'saint'],
  [ 9, 22, 'Maurice', 'saint'],
  [ 9, 23, 'Constant', 'saint'],
  [ 9, 24, 'Thècle', 'sainte'],
  [ 9, 25, 'Hermann', 'saint'],
  [ 9, 26, 'Côme', 'saint'],
  [ 9, 27, 'Vincent de Paul', 'saint'],
  [ 9, 28, 'Venceslas', 'saint'],
  [ 9, 29, 'Michel', 'saint'],
  [ 9, 30, 'Jérôme', 'saint'],
  [10,  1, 'Thérèse de l’Enfant Jésus', 'sainte'],
  [10,  2, 'Léger', 'saint'],
  [10,  3, 'Gérard', 'saint'],
  [10,  4, 'François d’Assise', 'saint'],
  [10,  5, 'Fleur', 'sainte'],
  [10,  6, 'Bruno', 'saint'],
  [10,  7, 'Serge', 'saint'],
  [10,  8, 'Pélagie', 'sainte'],
  [10,  9, 'Denis', 'saint'],
  [10, 10, 'Ghislain', 'saint'],
  [10, 11, 'Firmin', 'saint'],
  [10, 12, 'Wilfried', 'saint'],
  [10, 13, 'Géraud', 'saint'],
  [10, 14, 'Juste', 'saint'],
  [10, 15, 'Thérèse d’Avila', 'sainte'],
  [10, 16, 'Edwige', 'sainte'],
  [10, 17, 'Baudoin', 'saint'],
  [10, 18, 'Luc', 'saint'],
  [10, 19, 'René', 'saint'],
  [10, 20, 'Adeline', 'sainte'],
  [10, 21, 'Céline', 'sainte'],
  [10, 22, 'Élodie', 'sainte'],
  [10, 23, 'Jean de Capistran', 'saint'],
  [10, 24, 'Florentin', 'saint'],
  [10, 25, 'Crépin', 'saint'],
  [10, 26, 'Dimitri', 'saint'],
  [10, 27, 'Émeline', 'sainte'],
  [10, 28, 'Jude', 'saint'],
  [10, 29, 'Narcisse', 'saint'],
  [10, 30, 'Bienvenue', 'sainte'],
  [10, 31, 'Quentin', 'saint'],
  [11,  1, 'La Toussaint', 'fete'],
  [11,  2, 'Les défunts', 'fete'],
  [11,  3, 'Hubert', 'saint'],
  [11,  4, 'Charles', 'saint'],
  [11,  5, 'Sylvie', 'sainte'],
  [11,  6, 'Bertille', 'sainte'],
  [11,  7, 'Carine', 'sainte'],
  [11,  8, 'Geoffroy', 'saint'],
  [11,  9, 'Théodore', 'saint'],
  [11, 10, 'Léon', 'saint'],
  [11, 11, 'L’Armistice de 1918', 'fete'],
  [11, 12, 'Christian', 'saint'],
  [11, 13, 'Brice', 'saint'],
  [11, 14, 'Sidoine', 'saint'],
  [11, 15, 'Albert', 'saint'],
  [11, 16, 'Marguerite', 'sainte'],
  [11, 17, 'Élisabeth', 'sainte'],
  [11, 18, 'Aude', 'sainte'],
  [11, 19, 'Tanguy', 'saint'],
  [11, 20, 'Edmond', 'saint'],
  [11, 21, 'La Présence de Marie', 'fete'],
  [11, 22, 'Cécile', 'sainte'],
  [11, 23, 'Clément', 'saint'],
  [11, 24, 'Flora', 'sainte'],
  [11, 25, 'Catherine', 'sainte'],
  [11, 26, 'Delphine', 'sainte'],
  [11, 27, 'Séverin', 'saint'],
  [11, 28, 'Jacques de la Marche', 'saint'],
  [11, 29, 'Saturnin', 'saint'],
  [11, 30, 'André', 'saint'],
  [12,  1, 'Florence', 'sainte'],
  [12,  2, 'Viviane', 'sainte'],
  [12,  3, 'François-Xavier', 'saint'],
  [12,  4, 'Barbara', 'sainte'],
  [12,  5, 'Gérald', 'saint'],
  [12,  6, 'Nicolas', 'saint'],
  [12,  7, 'Ambroise', 'saint'],
  [12,  8, 'L’Immaculée Conception', 'fete'],
  [12,  9, 'Pierre Fourier', 'saint'],
  [12, 10, 'Romaric', 'saint'],
  [12, 11, 'Daniel', 'saint'],
  [12, 12, 'Jeanne-Françoise de Chantal', 'sainte'],
  [12, 13, 'Lucie', 'sainte'],
  [12, 14, 'Odile', 'sainte'],
  [12, 15, 'Ninon', 'sainte'],
  [12, 16, 'Alice', 'sainte'],
  [12, 17, 'Gaël', 'saint'],
  [12, 18, 'Gatien', 'saint'],
  [12, 19, 'Urbain', 'saint'],
  [12, 20, 'Théophile', 'saint'],
  [12, 21, 'Pierre Canisius', 'saint'],
  [12, 22, 'Françoise-Xavière', 'sainte'],
  [12, 23, 'Armand', 'saint'],
  [12, 24, 'Adèle', 'sainte'],
  [12, 25, 'Noël', 'fete'],
  [12, 26, 'Étienne', 'saint'],
  [12, 27, 'Jean', 'saint'],
  [12, 28, 'Les Saints Innocents', 'fete'],
  [12, 29, 'David', 'saint'],
  [12, 30, 'Roger', 'saint'],
];

export const JOURS_NOMMES: JourNomme[] = TABLE.map(([mois, jour, nom, genre], i) => ({
  mois,
  jour,
  nom,
  genre,
  ordinal: i + 1,
}));

/** Les deux jours qui n'ont pas de couverture à eux : les jokers. */
export const JOKERS_DU_CALENDRIER = [
  { numero: 53, nom: 'le jour de trop', date: '31 décembre', saint: 'Sylvestre' },
  { numero: 54, nom: 'le jour bissextile', date: '29 février', saint: null },
] as const;

/** Le joker d'une date, ou `null` : le 31 décembre et le 29 février. */
export function jokerDuJour(date: Date): (typeof JOKERS_DU_CALENDRIER)[number] | null {
  const mois = date.getMonth() + 1;
  const jour = date.getDate();
  return JOKERS_DU_CALENDRIER.find((j) => (j.numero === 53 ? mois === 12 && jour === 31 : mois === 2 && jour === 29)) ?? null;
}

/** Le prénom du jour, ou `null` les deux jours jokers. */
export function jourNomme(date: Date): JourNomme | null {
  return JOURS_NOMMES.find((j) => j.mois === date.getMonth() + 1 && j.jour === date.getDate()) ?? null;
}

/** Le prénom du jour, écrit simplement. */
export function nomDuJour(date: Date): string {
  const j = jourNomme(date);
  if (j) return j.nom;
  const joker = jokerDuJour(date);
  // Les deux jokers portent quand même leur fête : Sylvestre le 31 décembre,
  // et rien le 29 février — c'est le jour de trop, il n'a pas de prénom.
  return joker ? (joker.saint ?? joker.nom) : '';
}

/** Les jours d'un mois, dans l'ordre. */
export function joursDuMois(mois: number): JourNomme[] {
  return JOURS_NOMMES.filter((j) => j.mois === mois);
}
