/**
 * LE SHOP
 *
 * Tout ce qu'on peut louer, acheter, emprunter ou recevoir pour un mariage :
 * mobilier, vaisselle, décor, lumière, tenues, papeterie — et quelques objets
 * insolites qu'on ne trouve nulle part ailleurs. Chaque produit a sa page.
 */

export type ShopMode = 'location' | 'vente' | 'pret' | 'don';

export interface ShopCategory {
  id: string;
  label: string;
  description: string;
}

export interface ShopProduct {
  slug: string;
  name: string;
  category: string;
  modes: ShopMode[];
  /** Le mode principal, celui qu'on met en avant. */
  mode: ShopMode;
  price: string;
  /** Ce que le prix recouvre : « par table », « les 12 », « la journée »… */
  unit: string;
  image: string;
  tagline: string;
  description: string;
  specs: Array<{ label: string; value: string }>;
  includes: string[];
  /** Pour quel type d'ambiance c'est fait. */
  ambiances: string[];
  /** Les produits qui vont avec. */
  similar: string[];
  /** Le produit est-il mis en avant en page d'accueil du shop ? */
  featured?: boolean;
  /** Les objets qu'on ne loue pas tous les jours. */
  insolite?: boolean;
}

export const SHOP_MODES: Array<{ id: ShopMode; label: string; description: string }> = [
  { id: 'location', label: 'Location', description: 'Le temps d’un week-end, livré et repris' },
  { id: 'vente', label: 'Achat', description: 'Vous le gardez, le revendez ou l’offrez' },
  { id: 'pret', label: 'Prêt', description: 'Emprunté entre mariés, caution symbolique' },
  { id: 'don', label: 'Don', description: 'Offert à qui en aura besoin après vous' },
];

export const SHOP_CATEGORIES: ShopCategory[] = [
  { id: 'mobilier', label: 'Mobilier', description: 'Tables, chaises, banquettes, mange-debout' },
  { id: 'reception', label: 'Réception & Table', description: 'Vaisselle, verrerie, linge, bar' },
  { id: 'deco', label: 'Décor & Fleurs', description: 'Arches, suspensions, tapis, bougies' },
  { id: 'lumiere', label: 'Lumière & Son', description: 'Guirlandes, projecteurs, sonorisation' },
  { id: 'tenues', label: 'Tenues & Accessoires', description: 'Robes, costumes, voiles, bijoux' },
  { id: 'papeterie', label: 'Papeterie & Signalétique', description: 'Faire-part, menus, plans de table' },
  { id: 'insolite', label: 'Insolite', description: 'Les objets qui font parler tout le monde' },
];

export const SHOP_PRODUCTS: ShopProduct[] = [
  {
    slug: 'table-trestle-chene',
    name: 'Table trestle en chêne massif',
    category: 'mobilier',
    modes: ['location'],
    mode: 'location',
    price: '28 €',
    unit: 'la table, par jour',
    image: '/images/shop/mobilier.jpg',
    tagline: 'La grande table de banquet, brute et solide.',
    description:
      'Trois mètres de chêne massif, pieds trestle démontables, plateau non traité — elle prend les traces du repas et c’est tant mieux. C’est la table des banquets champêtres, des bergeries et des granges. Douze convives dessus, sans se serrer.',
    specs: [
      { label: 'Dimensions', value: '300 × 90 cm, hauteur 76 cm' },
      { label: 'Convives', value: '10 à 12 personnes' },
      { label: 'Matière', value: 'Chêne massif, finition brute' },
      { label: 'Transport', value: 'Pieds démontables, 45 kg' },
    ],
    includes: ['La table', 'Les deux trétaux', 'Le transport aller-retour', 'Le nettoyage'],
    ambiances: ['Champêtre', 'Bergerie', 'Grange', 'Brocante'],
    similar: ['chaise-paille-tressée', 'nappe-lin-lavé', 'vaisselle-gres-blanc', 'guirlande-ampoules'],
  },
  {
    slug: 'chaise-paille-tressée',
    name: 'Chaise paille tressée',
    category: 'mobilier',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '6 €',
    unit: 'la chaise',
    image: '/images/shop/mobilier.jpg',
    tagline: 'La chaise de ferme, toutes légèrement différentes.',
    description:
      'Assise paille tressée, structure hêtre. Nous en avons 240 en stock, toutes chinées, aucune identique — c’est exactement ce qui fait le charme d’un banquet dépareillé. À la location pour un week-end, ou à l’achat à partir de dix pièces.',
    specs: [
      { label: 'Stock', value: '240 chaises, modèles variés' },
      { label: 'Vente', value: '32 € la chaise à partir de 10' },
      { label: 'État', value: 'Chinées, nettoyées, renforcées' },
      { label: 'Transport', value: 'Palettes de 40, fourgon conseillé' },
    ],
    includes: ['Les chaises', 'Le transport', 'Le remplacement en cas de casse'],
    ambiances: ['Champêtre', 'Brocante', 'Traditionnel', 'Guinguette'],
    similar: ['table-trestle-chene', 'nappe-lin-lavé', 'guirlande-ampoules', 'photophore-laiton'],
    featured: true,
  },
  {
    slug: 'banquette-capiton',
    name: 'Banquette capitonnée longue',
    category: 'mobilier',
    modes: ['location'],
    mode: 'location',
    price: '90 €',
    unit: 'l’ensemble de 4 m',
    image: '/images/shop/mobilier.jpg',
    tagline: 'Pour asseoir la famille sans la séparer.',
    description:
      'Quatre modules de banquette capitonnée velours, à aligner le long d’un mur ou autour d’un arbre. Elle crée un vrai salon dehors, et se marie très bien avec des tables basses pour le cocktail.',
    specs: [
      { label: 'Dimensions', value: '4 modules de 1 m, assise 45 cm' },
      { label: 'Matière', value: 'Velours, piètement bois' },
      { label: 'Usage', value: 'Intérieur comme extérieur (temps sec)' },
    ],
    includes: ['Les 4 modules', 'Les coussins d’assise', 'Le transport'],
    ambiances: ['Cocktail', 'Lounge', 'Rooftop', 'Cosy'],
    similar: ['table-basse-brute', 'guirlande-ampoules', 'parasol-toile-ecrue', 'tapis-berbere'],
  },
  {
    slug: 'table-basse-brute',
    name: 'Table basse en bois brut',
    category: 'mobilier',
    modes: ['location', 'don'],
    mode: 'location',
    price: '18 €',
    unit: 'la pièce',
    image: '/images/shop/mobilier.jpg',
    tagline: 'Le coin salon qui manque toujours au cocktail.',
    description:
      'Plateau en orme brut sur piètement acier noir, 90 × 90 cm. Elles sont données en fin de saison aux couples qui les ont louées : nous ne stockons pas ce qui peut continuer à vivre ailleurs.',
    specs: [
      { label: 'Dimensions', value: '90 × 90 cm, hauteur 35 cm' },
      { label: 'Matière', value: 'Orme brut, acier noir' },
      { label: 'Don', value: 'Possible en fin de saison, sur demande' },
    ],
    includes: ['La table', 'Le transport'],
    ambiances: ['Cocktail', 'Industriel', 'Béton', 'Rooftop'],
    similar: ['banquette-capiton', 'tapis-berbere', 'photophore-laiton', 'guirlande-ampoules'],
  },
  {
    slug: 'vaisselle-gres-blanc',
    name: 'Vaisselle en grès blanc',
    category: 'reception',
    modes: ['location'],
    mode: 'location',
    price: '3,50 €',
    unit: 'le couvert',
    image: '/images/shop/vaisselle.jpg',
    tagline: 'Le couvert qui va avec tout.',
    description:
      'Assiettes plates et creuses en grès émaillé blanc mat, fabriquées par un atelier français. Épaisses, donc elles survivent au service par des amis, et assez belles pour du dressage à l’assiette.',
    specs: [
      { label: 'Composition', value: '1 plate, 1 creuse, 1 dessert' },
      { label: 'Matière', value: 'Grès émaillé, atelier français' },
      { label: 'Stock', value: 'Jusqu’à 400 couverts' },
      { label: 'Lavage', value: 'Fourni au retour, pas à votre charge' },
    ],
    includes: ['Les assiettes', 'La rotation si besoin', 'Le transport en caisses'],
    ambiances: ['Champêtre', 'Minimal', 'Traditionnel', 'Bord de mer'],
    similar: ['verrerie-fin-gold', 'couvert-métal-brossé', 'nappe-lin-lavé', 'table-trestle-chene'],
    featured: true,
  },
  {
    slug: 'verrerie-fin-gold',
    name: 'Verrerie fine à liseré doré',
    category: 'reception',
    modes: ['location'],
    mode: 'location',
    price: '2,80 €',
    unit: 'le verre',
    image: '/images/shop/vaisselle.jpg',
    tagline: 'Trois verres par personne, et rien de moins.',
    description:
      'Flûte, verre à eau et verre à vin, fin liseré doré peint à la main. Ce liseré s’abîme, forcément : c’est pour ça qu’on ne vous facture pas sa disparition au-delà de dix pièces par centaine.',
    specs: [
      { label: 'Composition', value: 'Flûte, eau, vin — au choix' },
      { label: 'Finition', value: 'Liseré doré peint à la main' },
      { label: 'Usure', value: '10 pièces par centaine tolérées' },
    ],
    includes: ['Les verres', 'Caisses isothermes', 'Le remplacement des casses'],
    ambiances: ['Traditionnel', 'Château', 'Reportage', 'Bord de mer'],
    similar: ['vaisselle-gres-blanc', 'couvert-métal-brossé', 'fontaine-champagne', 'nappe-lin-lavé'],
  },
  {
    slug: 'couvert-métal-brossé',
    name: 'Couverts en métal brossé',
    category: 'reception',
    modes: ['location', 'pret'],
    mode: 'location',
    price: '1,90 €',
    unit: 'le couvert',
    image: '/images/shop/vaisselle.jpg',
    tagline: 'Acier brossé, forme simple, service rapide.',
    description:
      'Cuillère, fourchette, couteau, petite cuillère : acier inoxydable brossé, prise en main large. Ils ne glissent pas des mains des serveurs, ce qui compte plus qu’on ne croit sur cent couverts.',
    specs: [
      { label: 'Composition', value: '4 pièces par couvert' },
      { label: 'Matière', value: 'Acier inoxydable brossé' },
      { label: 'Prêt', value: 'Possibilité après une location, entre mariés' },
    ],
    includes: ['Les couverts', 'Le transport', 'Le lavage au retour'],
    ambiances: ['Tous', 'Champêtre', 'Minimal', 'Traditionnel'],
    similar: ['vaisselle-gres-blanc', 'verrerie-fin-gold', 'nappe-lin-lavé', 'chemin-lit-affine'],
  },
  {
    slug: 'nappe-lin-lavé',
    name: 'Nappe en lin lavé',
    category: 'reception',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '12 €',
    unit: 'la nappe de 3 m',
    image: '/images/shop/vaisselle.jpg',
    tagline: 'Le lin froissé qui va avec tout le reste.',
    description:
      'Lin lavé 100 %, 3 m × 90 cm, dans quatre teintes naturelles : écrue, sable, gris perle, vert sauge. Le lin ne se repasse pas — plus il froisse, plus il est juste à sa place dans un banquet.',
    specs: [
      { label: 'Dimensions', value: '300 × 90 cm' },
      { label: 'Matière', value: 'Lin lavé 100 %' },
      { label: 'Teintes', value: 'Écru, sable, gris perle, vert sauge' },
      { label: 'Achat', value: '48 € la nappe, à garder' },
    ],
    includes: ['Les nappes', 'Le lavage', 'Le transport'],
    ambiances: ['Champêtre', 'Minimal', 'Méditerranéen', 'Brocante'],
    similar: ['table-trestle-chene', 'vaisselle-gres-blanc', 'chemin-lit-affine', 'photophore-laiton'],
  },
  {
    slug: 'chemin-lit-affine',
    name: 'Chemin de table en lin affiné',
    category: 'reception',
    modes: ['location'],
    mode: 'location',
    price: '5 €',
    unit: 'le chemin de 4 m',
    image: '/images/shop/vaisselle.jpg',
    tagline: 'Six mètres de lin plutôt que six bouquets.',
    description:
      'Bandes de lin lavé de 40 cm de large, posées en travers ou dans la longueur, à plat sur la table brute. C’est la version la plus économique d’un décor de table qui tient debout, et celle qui fonctionne le mieux en photo.',
    specs: [
      { label: 'Longueur', value: '4 m par pièce, ajustable' },
      { label: 'Largeur', value: '40 cm' },
      { label: 'Teintes', value: 'Écru, sable, terracotta' },
    ],
    includes: ['Les bandes', 'Le lavage', 'La pose si besoin'],
    ambiances: ['Champêtre', 'Bohème', 'Méditerranéen', 'Brocante'],
    similar: ['nappe-lin-lavé', 'vaisselle-gres-blanc', 'photo-support-laiton', 'photophore-laiton'],
  },
  {
    slug: 'fontaine-champagne',
    name: 'Fontaine à champagne',
    category: 'reception',
    modes: ['location'],
    mode: 'location',
    price: '85 €',
    unit: 'l’ensemble',
    image: '/images/champagne.jpg',
    tagline: 'Un peu kitsch, parfaitement assumé.',
    description:
      'Fontaine en verre en sept étages, coupe supérieure, éclairage intégré. On a longtemps hésité à la proposer : puis on a vu l’effet qu’elle produit sur un cocktail, à 20h, quand les lumières baissent. Elle est louée presque chaque week-end.',
    specs: [
      { label: 'Dimensions', value: 'H. 95 cm, 7 étages' },
      { label: 'Contenance', value: '42 flûtes (non fournies)' },
      { label: 'Éclairage', value: 'LED intégrée, prise standard' },
      { label: 'Montage', value: '30 minutes, à sec' },
    ],
    includes: ['La fontaine', 'L’éclairage', 'La flûte supérieure', 'La bâche de transport'],
    ambiances: ['Rooftop', 'Club', 'Las Vegas', 'Guinguette'],
    similar: ['verrerie-fin-gold', 'machine-fumee', 'boule-a-facettes', 'bar-mobile'],
    insolite: true,
  },
  {
    slug: 'bar-mobile',
    name: 'Bar mobile en bois de récupération',
    category: 'reception',
    modes: ['location'],
    mode: 'location',
    price: '110 €',
    unit: 'la journée',
    image: '/images/table-noir.jpg',
    tagline: 'Un vrai bar, monté en quinze minutes.',
    description:
      'Bar de 2 m en planches de palettes rabotées, avec étagère arrière, plan de travail inox et paillage pour les bacs. Il arrive démonté dans deux caisses, se monte à deux en un quart d’heure, et accepte les glacières professionnelles.',
    specs: [
      { label: 'Dimensions', value: '200 × 60 cm, hauteur 105 cm' },
      { label: 'Équipement', value: 'Étagère arrière, 2 bacs, inox' },
      { label: 'Montage', value: '15 minutes, deux personnes' },
    ],
    includes: ['Le bar démonté', 'Les bacs', 'Le transport', 'Le montage si souhaité'],
    ambiances: ['Champêtre', 'Brocante', 'Cocktail', 'Industriel'],
    similar: ['fontaine-champagne', 'verrerie-fin-gold', 'mange-debout-tonneau', 'enseigne-neon-prenoms'],
  },
  {
    slug: 'mange-debout-tonneau',
    name: 'Mange-debout en tonneau',
    category: 'mobilier',
    modes: ['location'],
    mode: 'location',
    price: '22 €',
    unit: 'la pièce',
    image: '/images/shop/mobilier.jpg',
    tagline: 'Cent personnes debout, et tout le monde s’assoit.',
    description:
      'Tonneau de chêne recyclé surmonté d’un plateau rond, hauteur 110 cm. Le mange-debout est l’objet qui sauve un cocktail : il permet de poser un verre, donc de tenir une conversation, donc de rester plus longtemps.',
    specs: [
      { label: 'Dimensions', value: 'Ø 80 cm, hauteur 110 cm' },
      { label: 'Matière', value: 'Tonneau de chêne recyclé' },
      { label: 'Stock', value: '30 pièces' },
    ],
    includes: ['Les mange-debout', 'Le transport', 'Les nappes assorties si besoin'],
    ambiances: ['Guinguette', 'Brocante', 'Champêtre', 'Méditerranéen'],
    similar: ['bar-mobile', 'table-basse-brute', 'guirlande-ampoules', 'vaisselle-gres-blanc'],
  },
  {
    slug: 'parasol-toile-ecrue',
    name: 'Parasol en toile écrue',
    category: 'deco',
    modes: ['location'],
    mode: 'location',
    price: '35 €',
    unit: 'la pièce',
    image: '/images/terrasse.jpg',
    tagline: 'De l’ombre véritable, au bon endroit.',
    description:
      'Parasol déporté de 3 m en toile écrue brute, mât aluminium, base lestable. À 32 °C, l’ombre n’est pas un détail de décoration : c’est ce qui permet aux grands-parents de rester au cocktail.',
    specs: [
      { label: 'Dimensions', value: 'Ø 300 cm, déporté' },
      { label: 'Toile', value: 'Écrue brute, déperlante' },
      { label: 'Base', value: 'Lestable 60 kg (fournie, à remplir)' },
    ],
    includes: ['Le parasol', 'La base', 'Le transport'],
    ambiances: ['Bord de mer', 'Rooftop', 'Méditerranéen', 'Garden party'],
    similar: ['banquette-capiton', 'table-basse-brute', 'guirlande-ampoules', 'tapis-berbere'],
  },
  {
    slug: 'arche-grasses-sechees',
    name: 'Arche en graminées séchées',
    category: 'deco',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '180 €',
    unit: 'la cérémonie',
    image: '/images/shop/arche.jpg',
    tagline: 'L’arche qui ne fanera pas avant la fin de la soirée.',
    description:
      'Structure en fer patiné et graminées séchées — blé noir, lagurus, pampas, eucalyptus stabilisé. Elle se monte en quinze minutes, se déplace à deux, et reste identique sur toutes les photos, ce que les fleurs fraîches ne garantissent pas.',
    specs: [
      { label: 'Dimensions', value: 'H. 250 cm, ouverture 150 cm' },
      { label: 'Composition', value: 'Graminées séchées, eucalyptus stabilisé' },
      { label: 'Montage', value: '15 minutes, deux personnes' },
      { label: 'Vente', value: '590 € en composition définitive' },
    ],
    includes: ['L’arche montée', 'Les socles', 'Le transport', 'Le démontage'],
    ambiances: ['Champêtre', 'Désert', 'Bergerie', 'Bohème'],
    similar: ['tapis-berbere', 'photophore-laiton', 'chandelier-fer-forge', 'guirlande-ampoules'],
    featured: true,
  },
  {
    slug: 'tapis-berbere',
    name: 'Tapis berbère ancien',
    category: 'deco',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '45 €',
    unit: 'le tapis, par jour',
    image: '/images/shop/arche.jpg',
    tagline: 'Dix tapis, et le lieu change de pays.',
    description:
      'Tapis anciens d’origine, laine et poils de chèvre, formats 2 × 3 m, chinés au fil des années. Posés en zone cocktail ou sous l’arche, ils règlent en une heure le problème des sols ingrats : béton, gravier, pelouse tondue.',
    specs: [
      { label: 'Formats', value: '200 × 300 cm environ' },
      { label: 'Origin', value: 'Maroc, Moyen Atlas, pièces anciennes' },
      { label: 'Stock', value: '14 tapis' },
    ],
    includes: ['Les tapis', 'Le sous-tapis de protection', 'Le transport'],
    ambiances: ['Désert', 'Bohème', 'Nomade', 'Bord de mer'],
    similar: ['arche-grasses-sechees', 'photophore-laiton', 'banquette-capiton', 'coussin-sol-fabrique'],
  },
  {
    slug: 'photophore-laiton',
    name: 'Photophores en laiton',
    category: 'deco',
    modes: ['location'],
    mode: 'location',
    price: '2,50 €',
    unit: 'la pièce',
    image: '/images/shop/lumieres.jpg',
    tagline: 'La bougie qui ne s’éteint pas au premier courant d’air.',
    description:
      'Verres en laiton cerclés, pour bougies chauffe-plat. Ils se disposent en ligne le long des tables ou en tapis au sol, et la lumière du laiton vieilli est incomparablement plus chaude qu’une LED.',
    specs: [
      { label: 'Dimensions', value: 'H. 9 cm, Ø 7 cm' },
      { label: 'Matière', value: 'Laiton vieilli, verre trempé' },
      { label: 'Stock', value: '300 pièces' },
      { label: 'Bougies', value: 'Fournies, allumage à votre charge' },
    ],
    includes: ['Les photophores', 'Les bougies', 'Le transport'],
    ambiances: ['Traditionnel', 'Champêtre', 'Méditerranéen', 'Bergerie'],
    similar: ['chandelier-fer-forge', 'nappe-lin-lavé', 'chemin-lit-affine', 'guirlande-ampoules'],
  },
  {
    slug: 'chandelier-fer-forge',
    name: 'Chandelier en fer forgé',
    category: 'deco',
    modes: ['location'],
    mode: 'location',
    price: '14 €',
    unit: 'la pièce',
    image: '/images/shop/lumieres.jpg',
    tagline: 'Cinq bougies, une grande ombre portée.',
    description:
      'Chandelier à cinq branches en fer forgé noir, hauteur 60 cm. Le noir et le fer se marient aussi bien avec du chêne brut qu’avec du béton banché, ce qui le rend utile dans presque tous les univers.',
    specs: [
      { label: 'Dimensions', value: 'H. 60 cm, 5 branches' },
      { label: 'Matière', value: 'Fer forgé patiné' },
      { label: 'Bougies', value: 'Cierges longs fournis' },
    ],
    includes: ['Les chandeliers', 'Les cierges', 'Le transport'],
    ambiances: ['Béton', 'Traditionnel', 'Industriel', 'Grange'],
    similar: ['photophore-laiton', 'chemin-lit-affine', 'enseigne-neon-prenoms', 'nappe-lin-lavé'],
  },
  {
    slug: 'guirlande-ampoules',
    name: 'Guirlande d’ampoules suspendues',
    category: 'lumiere',
    modes: ['location'],
    mode: 'location',
    price: '40 €',
    unit: 'les 20 mètres',
    image: '/images/shop/lumieres.jpg',
    tagline: 'La lumière qui fait tout tenir.',
    description:
      'Vingt mètres de câble noir avec ampoules culot E27 à filament, tous les 80 cm. Compte une guirlande pour dix mètres de table : tendue au-dessus du banquet, elle transforme une cour ou un pré en salle à manger à la nuit tombée.',
    specs: [
      { label: 'Longueur', value: '20 m, 25 ampoules' },
      { label: 'Ampoules', value: 'LED filament 2 W, 2 200 K' },
      { label: 'Installation', value: 'Crochets et câble porteur fournis' },
      { label: 'Alimentation', value: 'Prise standard, 1 par guirlande' },
    ],
    includes: ['La guirlande', 'Le câble porteur', 'Les crochets', 'La rallonge'],
    ambiances: ['Champêtre', 'Garden party', 'Cour', 'Bord de mer'],
    similar: ['projecteur-rasant', 'photophore-laiton', 'table-trestle-chene', 'machine-fumee'],
    featured: true,
  },
  {
    slug: 'projecteur-rasant',
    name: 'Projecteur rasant architectural',
    category: 'lumiere',
    modes: ['location'],
    mode: 'location',
    price: '65 €',
    unit: 'le projecteur, par nuit',
    image: '/images/shop/lumieres.jpg',
    tagline: 'Pour révéler un mur au lieu de l’éclairer.',
    description:
      'Projecteur LED 200 W orientable, faisceau réglable de 10° à 45°, avec gélatines ambrées et bleutées. Posé au sol rasant contre un mur de pierre ou une dalle de béton, il sculpte l’architecture et laisse le reste dans l’ombre.',
    specs: [
      { label: 'Puissance', value: '200 W LED, gradation intégrée' },
      { label: 'Faisceau', value: '10° à 45° réglable' },
      { label: 'Gélatines', value: 'Ambre, paille, bleu nuit' },
      { label: 'Alimentation', value: 'Prise 16 A, 1 par projecteur' },
    ],
    includes: ['Le projecteur', 'Le pied', 'Les gélatines', 'La rallonge'],
    ambiances: ['Béton', 'Industriel', 'Grange', 'Corse'],
    similar: ['guirlande-ampoules', 'machine-fumee', 'enseigne-neon-prenoms', 'chandelier-fer-forge'],
    insolite: true,
  },
  {
    slug: 'machine-fumee',
    name: 'Machine à fumée basse',
    category: 'lumiere',
    modes: ['location'],
    mode: 'location',
    price: '55 €',
    unit: 'la soirée',
    image: '/images/danse.jpg',
    tagline: 'La brume qui fait marcher les photos de danse.',
    description:
      'Machine à fumée lourde, réservoir 2,5 L, avec minuterie et télécommande. La fumée reste au sol : elle accroche les faisceaux, découpe les silhouettes sur la piste, et c’est souvent ce qui transforme une photo de danse ordinaire en image de concert.',
    specs: [
      { label: 'Réservoir', value: '2,5 L, 4 heures d’autonomie' },
      { label: 'Effet', value: 'Fumée lourde, reste au sol' },
      { label: 'Commande', value: 'Télécommande ou DMX' },
      { label: 'Précautions', value: 'Déconseillée sur parquet ciré' },
    ],
    includes: ['La machine', 'Le liquide', 'La télécommande', 'La bâche'],
    ambiances: ['Club', 'Béton', 'Techno', 'Cosmic'],
    similar: ['boule-a-facettes', 'projecteur-rasant', 'fontaine-champagne', 'guirlande-ampoules'],
    insolite: true,
  },
  {
    slug: 'boule-a-facettes',
    name: 'Boule à facettes et sa motorisation',
    category: 'lumiere',
    modes: ['location'],
    mode: 'location',
    price: '48 €',
    unit: 'la soirée',
    image: '/images/danse.jpg',
    tagline: 'Cinquante centimètres de nostalgie.',
    description:
      'Boule à facettes 50 cm, moteur silencieux et projecteur dédié. Elle a besoin d’obscurité totale et d’un plafond à 4 m minimum — chez nous, elle part surtout pour les soirées après 01h00, quand il ne reste plus que les vrais.',
    specs: [
      { label: 'Diamètre', value: '50 cm, miroirs 10 mm' },
      { label: 'Motorisation', value: 'Silencieuse, 3 tours/minute' },
      { label: 'Hauteur', value: 'Plafond de 4 m conseillé' },
      { label: 'Projecteur', value: 'LED blanche, fourni' },
    ],
    includes: ['La boule', 'Le moteur', 'Le projecteur', 'La suspension'],
    ambiances: ['Club', 'Vintage', 'Guinguette', 'Discothèque'],
    similar: ['machine-fumee', 'fontaine-champagne', 'projecteur-rasant', 'juke-box-vinyle'],
    insolite: true,
  },
  {
    slug: 'enseigne-neon-prenoms',
    name: 'Enseigne néon à vos prénoms',
    category: 'deco',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '120 €',
    unit: 'la commande',
    image: '/images/club-amour.jpg',
    tagline: 'Deux prénoms, un tube, et tout le monde se photographie.',
    description:
      'Néon LED souple sur plexiglas transparent, en écriture liée, dans seize couleurs. Fabriqué à vos prénoms en quinze jours. À la location pour le week-end, ou à l’achat si vous savez déjà où il finira chez vous.',
    specs: [
      { label: 'Délai', value: '15 jours ouvrés' },
      { label: 'Dimensions', value: 'Jusqu’à 120 cm de large' },
      { label: 'Couleurs', value: '16 teintes disponibles' },
      { label: 'Achat', value: '390 € au lieu de la location' },
      { label: 'Alimentation', value: 'Prise standard, variateur fourni' },
    ],
    includes: ['L’enseigne', 'Le variateur', 'La fixation', 'Le transport'],
    ambiances: ['Club', 'Rooftop', 'Las Vegas', 'Urbain'],
    similar: ['projecteur-rasant', 'machine-fumee', 'bar-mobile', 'franche-bise-decapsuleur'],
    insolite: true,
  },
  {
    slug: 'robe-simple-soie',
    name: 'Robe de mariée simple en soie',
    category: 'tenues',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '340 €',
    unit: 'la location 3 jours',
    image: '/images/shop/robe.jpg',
    tagline: 'Une seule ligne, aucune broderie.',
    description:
      'Robe fluide en soie sauvage, bretelles fines, dos nu, traîne courte. Coupe droite sans baleinage, taille 34 à 42, retouches possibles par notre atelier. La version la plus calme de la robe de mariée, celle qui laisse toute la place au lieu et à la lumière.',
    specs: [
      { label: 'Matière', value: 'Soie sauvage doublée' },
      { label: 'Tailles', value: '34 à 42, quatre coloris' },
      { label: 'Retouches', value: 'Incluses, atelier partenaire' },
      { label: 'Achat', value: '1 180 € en pièce neuve' },
    ],
    includes: ['La robe', 'Le pressing avant et après', 'Les retouches', 'La housse'],
    ambiances: ['Minimal', 'Corse', 'Reportage', 'Bord de mer'],
    similar: ['voile-cathedral-tulle', 'costume-laine-imperiale', 'bouquet-champetre-seche', 'chaussures-cuir-souple'],
    featured: true,
  },
  {
    slug: 'costume-laine-imperiale',
    name: 'Costume de cérémonie en laine froide',
    category: 'tenues',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '190 €',
    unit: 'la location 3 jours',
    image: '/images/shop/robe.jpg',
    tagline: 'Un costume qui respire, même en juillet.',
    description:
      'Laine froide 240 g, coupe demi-mesure, veston deux boutons et pantalon à pinces. Pour les mariages d’été, c’est la seule matière qui tient la journée entière sans transpirer dans les photos de 18h.',
    specs: [
      { label: 'Matière', value: 'Laine froide, 240 g/m²' },
      { label: 'Coupe', value: 'Demi-mesure, retouches incluses' },
      { label: 'Tailles', value: '44 à 60' },
      { label: 'Achat', value: '590 € sur mesure' },
    ],
    includes: ['Le veston', 'Le pantalon', 'Les retouches', 'Le pressing'],
    ambiances: ['Traditionnel', 'Château', 'New-York', 'Rooftop'],
    similar: ['noeud-papillon-soie', 'robe-simple-soie', 'chaussures-cuir-souple', 'alliances-or-blanc'],
  },
  {
    slug: 'voile-cathedral-tulle',
    name: 'Voile cathédrale en tulle',
    category: 'tenues',
    modes: ['location', 'pret'],
    mode: 'location',
    price: '85 €',
    unit: 'la location',
    image: '/images/shop/robe.jpg',
    tagline: 'Trois mètres de tulle, et la cérémonie change de ton.',
    description:
      'Voile cathédrale en tulle de soie, 3 m, bords non ourlés, peigne en corne. Il se porte à l’église puis se retire d’un geste pour le cocktail — et il se prête volontiers entre mariées quand il a servi une fois.',
    specs: [
      { label: 'Longueur', value: '300 cm' },
      { label: 'Matière', value: 'Tulle de soie, bords bruts' },
      { label: 'Fixation', value: 'Peigne en corne fourni' },
      { label: 'Prêt', value: 'Offert à une autre mariée après usage' },
    ],
    includes: ['Le voile', 'Le peigne', 'Le pressing'],
    ambiances: ['Traditionnel', 'Château', 'Église', 'Reportage'],
    similar: ['robe-simple-soie', 'bouquet-champetre-seche', 'alliances-or-blanc', 'livre-messe-imprime'],
  },
  {
    slug: 'noeud-papillon-soie',
    name: 'Nœud papillon en soie sauvage',
    category: 'tenues',
    modes: ['location', 'vente', 'pret'],
    mode: 'vente',
    price: '45 €',
    unit: 'la pièce',
    image: '/images/shop/robe.jpg',
    tagline: 'Le détail qui sauve un costume loué.',
    description:
      'Nœud papillon à nouer, soie sauvage teintée à la main, onze coloris. Le nœud pré-noué se voit à vingt mètres sur une photo ; celui-ci non. Un atelier de la Drôme les coud un par un.',
    specs: [
      { label: 'Matière', value: 'Soie sauvage teintée main' },
      { label: 'Coloris', value: '11 teintes, dont terracotta et sauge' },
      { label: 'Forme', value: 'À nouer, deux tailles' },
      { label: 'Prêt', value: 'Échange possible après le mariage' },
    ],
    includes: ['Le nœud papillon', 'La pochette assortie'],
    ambiances: ['Traditionnel', 'Château', 'Champêtre', 'New-York'],
    similar: ['costume-laine-imperiale', 'boutonniere-sechee', 'chaussures-cuir-souple', 'alliances-or-blanc'],
  },
  {
    slug: 'chaussures-cuir-souple',
    name: 'Chaussures en cuir souple',
    category: 'tenues',
    modes: ['location', 'don'],
    mode: 'location',
    price: '38 €',
    unit: 'la location',
    image: '/images/shop/robe.jpg',
    tagline: 'Belles à la cérémonie, tenables jusqu’à 3h.',
    description:
      'Derby en cuir souple, semelle cuir cousue, talon 2 cm. Le pire ennemi d’un mariage n’est pas la pluie, c’est la mariée qui enlève ses chaussures à 21h. Celles-ci sont faites pour danser.',
    specs: [
      { label: 'Matière', value: 'Cuir pleine fleur, cousu main' },
      { label: 'Semelle', value: 'Cuir, ressemelage possible' },
      { label: 'Pointures', value: '35 à 46' },
      { label: 'Don', value: 'Données à une association après la saison' },
    ],
    includes: ['Les chaussures', 'Les embauchoirs', 'Le cirage'],
    ambiances: ['Tous', 'Traditionnel', 'Rooftop', 'Champêtre'],
    similar: ['robe-simple-soie', 'costume-laine-imperiale', 'noeud-papillon-soie', 'confort-danse-semelles'],
  },
  {
    slug: 'alliances-or-blanc',
    name: 'Alliances en or blanc recyclé',
    category: 'tenues',
    modes: ['vente'],
    mode: 'vente',
    price: '680 €',
    unit: 'la paire',
    image: '/images/alliances.jpg',
    tagline: 'De l’or qui existe déjà, refondu pour vous.',
    description:
      'Or blanc 18 carats issu de bijoux recyclés, finition satinée, gravure intérieure offerte. Nous travaillons avec un atelier qui ne mine rien : la matière vient de rachats, ce qui divise l’empreinte par six sans rien changer au métal.',
    specs: [
      { label: 'Matière', value: 'Or blanc 750/1000 recyclé' },
      { label: 'Finition', value: 'Satinée ou polie' },
      { label: 'Largeur', value: '2 à 4 mm' },
      { label: 'Gravure', value: 'Par nos soins, deux lignes' },
      { label: 'Délai', value: '3 semaines' },
    ],
    includes: ['Les deux alliances', 'La gravure', 'Le coffret et l’écrin'],
    ambiances: ['Tous', 'Minimal', 'Traditionnel', 'Reportage'],
    similar: ['robe-simple-soie', 'costume-laine-imperiale', 'noeud-papillon-soie', 'bouquet-champetre-seche'],
  },
  {
    slug: 'faire-part-risographie',
    name: 'Faire-part en risographie',
    category: 'papeterie',
    modes: ['vente', 'pret'],
    mode: 'vente',
    price: '2,40 €',
    unit: 'le faire-part, à partir de 50',
    image: '/images/punk-papier.jpg',
    tagline: 'Deux passages, trois couleurs, des hasards heureux.',
    description:
      'Risographie en deux passages, papier 160 g recyclé, trois teintes d’encre (noir, vermillon, vert prairie). Chaque exemplaire est légèrement décalé — l’imperfection fait partie du procédé, et personne n’a jamais fait un mariage identique.',
    specs: [
      { label: 'Papier', value: 'Création 160 g 100 % recyclé' },
      { label: 'Encres', value: 'Noir, vermillon, vert prairie' },
      { label: 'Minimum', value: '50 exemplaires' },
      { label: 'Délai', value: '10 jours ouvrés' },
    ],
    includes: ['Les faire-part', 'Les enveloppes', 'Le modèle personnalisé', 'Une plaque souvenir'],
    ambiances: ['Punk', 'Urbain', 'Béton', 'Brocante'],
    similar: ['menu-calligraphie', 'plan-table-ardoise', 'livre-messe-imprime', 'enseigne-neon-prenoms'],
  },
  {
    slug: 'menu-calligraphie',
    name: 'Menus calligraphiés à la main',
    category: 'papeterie',
    modes: ['vente', 'pret'],
    mode: 'vente',
    price: '4,50 €',
    unit: 'le menu',
    image: '/images/table-noir.jpg',
    tagline: 'Un menu par table, écrit à la plume.',
    description:
      'Encres de couleur, plume et calligraphie à la main, un menu par table et deux affiches pour le buffet. Il existe une police qui imite l’écriture ; au dos d’une porte de grange, on voit immédiatement la différence.',
    specs: [
      { label: 'Support', value: 'Papier chiffon 250 g, format A5' },
      { label: 'Calligraphie', value: 'À la plume, trois écritures' },
      { label: 'Délai', value: '7 jours après validation du menu' },
      { label: 'Prêt', value: 'Le modèle peut être réutilisé par d’autres couples' },
    ],
    includes: ['Les menus', 'Les deux affiches', 'Les supports bois'],
    ambiances: ['Traditionnel', 'Château', 'Champêtre', 'Méditerranéen'],
    similar: ['plan-table-ardoise', 'faire-part-risographie', 'livre-messe-imprime', 'etiquettes-place-cuir'],
  },
  {
    slug: 'plan-table-ardoise',
    name: 'Plan de table sur ardoise',
    category: 'papeterie',
    modes: ['location', 'pret'],
    mode: 'location',
    price: '25 €',
    unit: 'l’ardoise',
    image: '/images/table-noir.jpg',
    tagline: 'On écrit, on efface, on recommence.',
    description:
      'Ardoise naturelle de 80 × 60 cm sur support bois, avec craies et chiffon. Trois semaines avant un mariage, un plan de table change toujours deux fois : l’ardoise évite de réimprimer le travail de la veille.',
    specs: [
      { label: 'Dimensions', value: '80 × 60 cm, support bois' },
      { label: 'Matériel', value: 'Craies blanches, chiffon, éponge' },
      { label: 'Prêt', value: 'Prêtée à un autre couple après usage' },
    ],
    includes: ['L’ardoise', 'Les craies', 'Le chevalet'],
    ambiances: ['Champêtre', 'Brocante', 'Punk', 'Grange'],
    similar: ['menu-calligraphie', 'etiquettes-place-cuir', 'faire-part-risographie', 'livre-messe-imprime'],
  },
  {
    slug: 'livre-messe-imprime',
    name: 'Livret de messe imprimé',
    category: 'papeterie',
    modes: ['vente'],
    mode: 'vente',
    price: '2,90 €',
    unit: 'le livret, à partir de 60',
    image: '/images/noir-blanc-entree.jpg',
    tagline: 'Les chants, les lectures, et de quoi suivre.',
    description:
      'Livret 16 pages, papier bouffant, reliure piqûre à cheval, typographie classique. Il contient les chants, les textes choisis, la liste des témoins et un mot de remerciement — ce que la moitié de l’assemblée cherchera pendant la messe.',
    specs: [
      { label: 'Format', value: 'A5, 16 pages' },
      { label: 'Reliure', value: 'Piqûre à cheval' },
      { label: 'Minimum', value: '60 exemplaires' },
      { label: 'Délai', value: '12 jours ouvrés' },
    ],
    includes: ['Les livrets', 'La mise en page', 'Le fichier source'],
    ambiances: ['Traditionnel', 'Château', 'Église', 'Classique'],
    similar: ['menu-calligraphie', 'faire-part-risographie', 'etiquettes-place-cuir', 'voile-cathedral-tulle'],
  },
  {
    slug: 'etiquettes-place-cuir',
    name: 'Marque-places en cuir tanné',
    category: 'papeterie',
    modes: ['vente', 'pret'],
    mode: 'vente',
    price: '3,20 €',
    unit: 'la pièce, gravée',
    image: '/images/table-noir.jpg',
    tagline: 'Un prénom gravé, que les invités gardent.',
    description:
      'Chutes de cuir tanné végétal récupérées chez un maroquinier, gravées au fer à vos prénoms. Les invités les emportent une fois sur deux — c’est même le but, et c’est aussi ce qui rend le prêt possible entre couples.',
    specs: [
      { label: 'Matière', value: 'Cuir tanné végétal, chutes récupérées' },
      { label: 'Format', value: '7 × 4 cm, 6 teintes' },
      { label: 'Gravure', value: 'À chaud, prénoms inclus' },
      { label: 'Prêt', value: 'Revendues ou prêtées après usage' },
    ],
    includes: ['Les marque-places gravés', 'Le ruban', 'Le pochon de rangement'],
    ambiances: ['Champêtre', 'Minimal', 'Brocante', 'Méditerranéen'],
    similar: ['menu-calligraphie', 'plan-table-ardoise', 'faire-part-risographie', 'chemise-lin-invites'],
  },
  {
    slug: 'bouquet-champetre-seche',
    name: 'Bouquet champêtre de fleurs séchées',
    category: 'deco',
    modes: ['location', 'vente', 'don'],
    mode: 'vente',
    price: '85 €',
    unit: 'le bouquet',
    image: '/images/bouquet.jpg',
    tagline: 'Il sèche, il reste, il finit sur une étagère.',
    description:
      'Composé de fleurs de saison séchées naturellement, tige par tige, dans les tons paille et terracotta. Le bouquet de mariée se jette ; celui-ci se garde. Les bouquets revenus sont donnés à un service de soins palliatifs de la région.',
    specs: [
      { label: 'Dimensions', value: 'Ø 25 cm environ, 45 cm de long' },
      { label: 'Composition', value: 'Fleurs de saison séchées sur pied' },
      { label: 'Teintes', value: 'Paille, terracotta, sauge' },
      { label: 'Don', value: 'Bouquets revenus donnés à une association' },
    ],
    includes: ['Le bouquet', 'Le ruban de soie', 'La housse de transport'],
    ambiances: ['Champêtre', 'Corse', 'Bohème', 'Désert'],
    similar: ['boutonniere-sechee', 'arche-grasses-sechees', 'couronne-cheveux-sechee', 'robe-simple-soie'],
  },
  {
    slug: 'boutonniere-sechee',
    name: 'Boutonnière séchée',
    category: 'deco',
    modes: ['vente', 'pret', 'don'],
    mode: 'vente',
    price: '9 €',
    unit: 'la pièce',
    image: '/images/bouquet.jpg',
    tagline: 'Pour les témoins, les papas et les grands-pères.',
    description:
      'Une tige de blé noir, un eucalyptus stabilisé, un lien de raphia. Elle ne s’effondre pas à la chaleur, contrairement aux fleurs fraîches — et après le mariage, elle se prête ou se donne à un autre couple.',
    specs: [
      { label: 'Dimensions', value: '12 cm environ' },
      { label: 'Attache', value: 'Épingle fournie, invisible' },
      { label: 'Prêt', value: 'Rendues puis prêtées au couple suivant' },
    ],
    includes: ['La boutonnière', 'L’épingle', 'Le pochon'],
    ambiances: ['Champêtre', 'Corse', 'Traditionnel', 'Bohème'],
    similar: ['bouquet-champetre-seche', 'couronne-cheveux-sechee', 'noeud-papillon-soie', 'arche-grasses-sechees'],
  },
  {
    slug: 'couronne-cheveux-sechee',
    name: 'Couronne de fleurs séchées',
    category: 'deco',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '32 €',
    unit: 'la couronne',
    image: '/images/bouquet.jpg',
    tagline: 'Pour la demoiselle d’honneur, ou pour vous.',
    description:
      'Couronne montée sur fil garni, diamètre ajustable, fleurs séchées et graminées. À la location, nous la remontons entre chaque mariage ; à l’achat, elle finit sa vie en décoration murale.',
    specs: [
      { label: 'Diamètre', value: 'Ajustable de 18 à 24 cm' },
      { label: 'Composition', value: 'Graminées, fleurs séchées, fil garni' },
      { label: 'Achat', value: '54 € en composition définitive' },
    ],
    includes: ['La couronne', 'La réparation si besoin', 'La housse'],
    ambiances: ['Champêtre', 'Bohème', 'Corse', 'Bord de mer'],
    similar: ['bouquet-champetre-seche', 'boutonniere-sechee', 'voile-cathedral-tulle', 'arche-grasses-sechees'],
  },
  {
    slug: 'coussin-sol-fabrique',
    name: 'Coussins de sol fabriqués main',
    category: 'mobilier',
    modes: ['location', 'vente', 'don'],
    mode: 'location',
    price: '8 €',
    unit: 'le coussin',
    image: '/images/shop/arche.jpg',
    tagline: 'Pour les enfants, et pour ceux qui n’en sont plus.',
    description:
      'Coussins 50 × 50 en tissus recyclés, garnis de mousse densité 30. Disposés sous l’arche ou autour des tables basses, ils règlent le problème des petits invités et des grands-parents en même temps.',
    specs: [
      { label: 'Dimensions', value: '50 × 50 cm, épaisseur 12 cm' },
      { label: 'Garnissage', value: 'Mousse densité 30, déhoussable' },
      { label: 'Tissus', value: 'Recyclés, six coloris' },
      { label: 'Don', value: 'Donnés à une crèche après la saison' },
    ],
    includes: ['Les coussins', 'Les housses de rechange', 'Le transport'],
    ambiances: ['Champêtre', 'Nomade', 'Bohème', 'Bord de mer'],
    similar: ['tapis-berbere', 'banquette-capiton', 'table-basse-brute', 'arche-grasses-sechees'],
  },
  {
    slug: 'chemise-lin-invites',
    name: 'Chemise en lin pour les invités',
    category: 'tenues',
    modes: ['pret', 'don'],
    mode: 'pret',
    price: 'Gratuit',
    unit: 'au prêt, caution 20 €',
    image: '/images/shop/robe.jpg',
    tagline: 'Un mariage à 38 °C, on vous prête de quoi tenir.',
    description:
      'Quarante chemises en lin lavé, du S au XXL, dans quatre teintes claires. Elles circulent gratuitement depuis trois ans entre les mariages de l’été : on les emprunte, on les rend lavées, elles repartent ailleurs. C’est notre manière de faire circuler ce qui ne sert qu’une fois.',
    specs: [
      { label: 'Tailles', value: 'S à XXL, 40 pièces' },
      { label: 'Matière', value: 'Lin lavé, quatre teintes claires' },
      { label: 'Prêt', value: 'Gratuit, caution de 20 € restituée' },
      { label: 'Entretien', value: 'Rendues lavées, sèche-linge interdit' },
    ],
    includes: ['La chemise', 'Le cintre', 'La housse'],
    ambiances: ['Désert', 'Corse', 'Bord de mer', 'Été'],
    similar: ['costume-laine-imperiale', 'chaussures-cuir-souple', 'confort-danse-semelles', 'parasol-toile-ecrue'],
  },
  {
    slug: 'confort-danse-semelles',
    name: 'Semelles de confort pour la danse',
    category: 'tenues',
    modes: ['pret', 'don'],
    mode: 'pret',
    price: 'Gratuit',
    unit: 'au prêt',
    image: '/images/danse.jpg',
    tagline: 'Pour finir la soirée debout.',
    description:
      'Semelles adhésives et coussinets d’avant-pied, à coller sous n’importe quelle chaussure. On en donne une paire à chaque mariée et à chaque invité qui demande après 22h : c’est le geste le plus apprécié de tout notre stock.',
    specs: [
      { label: 'Composition', value: 'Gel polymère, adhésif repositionnable' },
      { label: 'Tailles', value: 'Universelles, à découper' },
      { label: 'Don', value: 'Données par paires, à qui en a besoin' },
    ],
    includes: ['La paire', 'Les coussinets d’avant-pied'],
    ambiances: ['Tous', 'Club', 'Traditionnel', 'Rooftop'],
    similar: ['chaussures-cuir-souple', 'robe-simple-soie', 'chemise-lin-invites', 'fontaine-champagne'],
    insolite: true,
  },
  {
    slug: 'juke-box-vinyle',
    name: 'Juke-box à vinyles',
    category: 'insolite',
    modes: ['location'],
    mode: 'location',
    price: '260 €',
    unit: 'la soirée complète',
    image: '/images/danse.jpg',
    tagline: 'Cent 45 tours, et les invités font le DJ.',
    description:
      'Juke-box restauré de 1963, fonctionnant à la pièce ou en mode libre, avec cent quarante 45 tours sélectionnés (Soul, Rock, Chanson). On l’allume après le dîner : les oncles y passent la soirée, et c’est souvent la meilleure playlist de la nuit.',
    specs: [
      { label: 'Année', value: '1963, restauré, mécanique révisée' },
      { label: 'Stock de disques', value: '140 vinyles 45 tours' },
      { label: 'Fonctionnement', value: 'Pièce, jeton ou mode libre' },
      { label: 'Encombrement', value: '90 × 70 × 150 cm, 140 kg' },
      { label: 'Alimentation', value: '220 V, 300 W' },
    ],
    includes: ['Le juke-box', 'Les vinyles', 'Les jetons', 'Le transport et l’installation'],
    ambiances: ['Vintage', 'Guinguette', 'Dinatoire', 'Soirée'],
    similar: ['boule-a-facettes', 'machine-fumee', 'franche-bise-decapsuleur', 'fontaine-champagne'],
    insolite: true,
  },
  {
    slug: 'franche-bise-decapsuleur',
    name: 'Franche-bise et décapsuleur mural',
    category: 'insolite',
    modes: ['location', 'vente'],
    mode: 'location',
    price: '75 €',
    unit: 'l’ensemble',
    image: '/images/table-noir.jpg',
    tagline: 'Pour les mariages où les bouteilles ne font pas semblant.',
    description:
      'Franche-bise montée sur billot de chêne de 90 kg, avec décapsuleur mural en fonte et seau à bouteilles. Posée près du bar, elle devient l’attraction de la soirée — et elle encaisse sans bouger.',
    specs: [
      { label: 'Base', value: 'Billot de chêne 90 kg' },
      { label: 'Accessoires', value: 'Franche-bise acier, décapsuleur fonte' },
      { label: 'Usage', value: 'Bouteilles de bière et champagne' },
    ],
    includes: ['Le billot', 'Le franche-bise', 'Le décapsuleur', 'Le seau à bouteilles'],
    ambiances: ['Guinguette', 'Corse', 'Punk', 'Grange'],
    similar: ['bar-mobile', 'enseigne-neon-prenoms', 'mange-debout-tonneau', 'juke-box-vinyle'],
    insolite: true,
  },
  {
    slug: 'photo-support-laiton',
    name: 'Support photo en laiton et bois',
    category: 'insolite',
    modes: ['location'],
    mode: 'location',
    price: '95 €',
    unit: 'le support complet',
    image: '/images/shop/vaisselle.jpg',
    tagline: 'Un arc-en-ciel de photos, à faire tourner.',
    description:
      'Structure en laiton et pin massif en forme d’arche, cinquante pinces en laiton et un banc pour les invités. Les photos instantanées s’accrochent au fil au fur et à mesure, et à minuit le mur est plein : c’est ce que les mariés regardent le plus, après.',
    specs: [
      { label: 'Dimensions', value: 'H. 180 cm, larg. 150 cm' },
      { label: 'Matière', value: 'Laiton patiné, pin massif' },
      { label: 'Pinces', value: '50 pinces laiton' },
      { label: 'Appareil', value: 'Instantané non fourni (option 40 €)' },
    ],
    includes: ['La structure', 'Les pinces', 'Les tiges filetées de réglage'],
    ambiances: ['Champêtre', 'Rooftop', 'Traditionnel', 'Bohème'],
    similar: ['photophore-laiton', 'guirlande-ampoules', 'enseigne-neon-prenoms', 'plan-table-ardoise'],
    insolite: true,
  },
  {
    slug: 'cabine-instantanee-argentique',
    name: 'Cabine instantanée argentique',
    category: 'insolite',
    modes: ['location'],
    mode: 'location',
    price: '320 €',
    unit: 'la soirée, pellicules incluses',
    image: '/images/shop/lumieres.jpg',
    tagline: 'Pas de numérique, pas de filtre, pas d’écran.',
    description:
      'Une cabine en bois habillée de tissu, un appareil argentique à déclenchement mécanique, un flash de studio et deux cents poses. Les invités entrent, sortent trois minutes plus tard avec une photo humide qu’ils accrochent au mur. Le rendu est imparfait, et c’est tant mieux.',
    specs: [
      { label: 'Poses', value: '200 incluses, 60 € le lot de 100' },
      { label: 'Rendu', value: 'Argentique, tirage instantané' },
      { label: 'Empreinte', value: '360 × 220 × 240 cm au sol' },
      { label: 'Installation', value: 'Prise 16 A et 12 m² au calme' },
      { label: 'Animation', value: 'Un opérateur présent toute la soirée' },
    ],
    includes: ['La cabine', 'Les pellicules', 'L’opérateur', 'Le fond en toile écrue'],
    ambiances: ['Rooftop', 'Vintage', 'Club', 'Traditionnel'],
    similar: ['photo-support-laiton', 'enseigne-neon-prenoms', 'machine-fumee', 'boule-a-facettes'],
    insolite: true,
    featured: true,
  },
];

/** Les produits d'une catégorie, ou tous. */
export function productsByCategory(categoryId: string | null): ShopProduct[] {
  if (!categoryId || categoryId === 'tout') return SHOP_PRODUCTS;
  return SHOP_PRODUCTS.filter((p) => p.category === categoryId);
}

export function productBySlug(slug: string): ShopProduct | undefined {
  return SHOP_PRODUCTS.find((p) => p.slug === slug);
}

/** Les produits qui vont avec celui qu'on regarde. */
export function similarProducts(product: ShopProduct, limit = 4): ShopProduct[] {
  const direct = product.similar
    .map((slug) => productBySlug(slug))
    .filter((p): p is ShopProduct => Boolean(p));
  if (direct.length >= limit) return direct.slice(0, limit);
  const complement = SHOP_PRODUCTS.filter(
    (p) => p.category === product.category && p.slug !== product.slug && !direct.includes(p),
  );
  return [...direct, ...complement].slice(0, limit);
}

/** Le libellé du mode, tel qu'il s'affiche sur les cartes. */
export function modeLabel(mode: ShopMode): string {
  return SHOP_MODES.find((m) => m.id === mode)?.label ?? mode;
}
