-- ============================================================================
--  WEDDING SITE — schéma Supabase (PostgreSQL)
--
--  Le dépôt contient onze endpoints serverless mais aucune définition de base :
--  ce fichier rend l’infrastructure reproductible. À exécuter dans l’éditeur SQL
--  du projet Supabase (ou via `supabase db push` avec la CLI).
--
--  Les colonnes reproduisent exactement les types de `src/lib/types.ts`, qui
--  sont eux-mêmes alignés sur ce que lisent et écrivent les endpoints.
-- ============================================================================

-- Un site de mariage : identité, date, lieu, apparence et contenus du hero.
create table if not exists public.wedding_sites (
  id              bigint generated by default as identity primary key,
  slug            text not null unique,
  partner1        text not null default '',
  partner2        text not null default '',
  wedding_date    date,
  venue           text not null default '',
  city            text not null default '',
  -- Apparence : identifiants des catalogues de src/lib/weddingStyles.ts
  style           text not null default 'editorial',
  phase           text not null default 'avant',        -- avant | pendant | apres
  typography      text not null default 'spatial',
  accent_color    text not null default '#16171A',
  button_style    text not null default 'pill',         -- pill | soft | square
  shape           text not null default 'soft',         -- soft | sharp | round
  layout          text not null default 'magazine',     -- minimal | magazine | immersif | galerie
  animation_level text not null default 'fluide',       -- calme | fluide | spectaculaire
  -- Contenus
  hero_photo      text not null default '',
  hero_title      text not null default '',
  hero_subtitle   text not null default '',
  story_title     text not null default '',
  story_text      text not null default '',
  story_photo     text not null default '',
  announcement    text not null default '',
  contact_email   text not null default '',
  contact_phone   text not null default '',
  published       boolean not null default false,
  created_at      timestamptz not null default now()
);

create index if not exists wedding_sites_slug_idx on public.wedding_sites (slug);

-- Ordre et visibilité des sections (clés lues par SECTION_COMPONENTS).
create table if not exists public.site_sections (
  id          bigint generated by default as identity primary key,
  site_id     bigint not null references public.wedding_sites (id) on delete cascade,
  section_key text not null,   -- hero | histoire | programme | lieux | infos | rsvp | cagnotte | galerie | faq | contact | footer
  title       text not null default '',
  visible     boolean not null default true,
  position    integer not null default 0
);

create index if not exists site_sections_site_idx on public.site_sections (site_id, position);

-- Déroulé du Jour J.
create table if not exists public.programme_events (
  id          bigint generated by default as identity primary key,
  site_id     bigint not null references public.wedding_sites (id) on delete cascade,
  event_time  text not null default '',
  title       text not null default '',
  description text not null default '',
  place       text not null default '',
  icon        text not null default 'clock',
  position    integer not null default 0
);

create index if not exists programme_events_site_idx on public.programme_events (site_id, position);

-- Informations pratiques (parking, hébergements, dress code, lieux…).
create table if not exists public.infos_pratiques (
  id          bigint generated by default as identity primary key,
  site_id     bigint not null references public.wedding_sites (id) on delete cascade,
  category    text not null default '',
  title       text not null default '',
  detail      text not null default '',
  event_time  text not null default '',
  link_label  text not null default '',
  position    integer not null default 0
);

create index if not exists infos_pratiques_site_idx on public.infos_pratiques (site_id, position);

-- Galerie du site (les photos sont stockées dans le bucket `wedding-media`).
create table if not exists public.gallery_photos (
  id         bigint generated by default as identity primary key,
  site_id    bigint not null references public.wedding_sites (id) on delete cascade,
  url        text not null default '',
  caption    text not null default '',
  position   integer not null default 0,
  is_private boolean not null default false
);

create index if not exists gallery_photos_site_idx on public.gallery_photos (site_id, position);

create table if not exists public.faqs (
  id       bigint generated by default as identity primary key,
  site_id  bigint not null references public.wedding_sites (id) on delete cascade,
  question text not null default '',
  answer   text not null default '',
  position integer not null default 0
);

create index if not exists faqs_site_idx on public.faqs (site_id, position);

-- Moments proposés aux invités dans le formulaire RSVP.
create table if not exists public.rsvp_events (
  id          bigint generated by default as identity primary key,
  site_id     bigint not null references public.wedding_sites (id) on delete cascade,
  name        text not null default '',
  description text not null default '',
  position    integer not null default 0
);

create index if not exists rsvp_events_site_idx on public.rsvp_events (site_id, position);

-- Réponses des invités. Contient des données personnelles (email, régimes,
-- allergies, coordonnées) : à protéger en priorité (voir plus bas).
create table if not exists public.rsvp_responses (
  id             bigint generated by default as identity primary key,
  site_id        bigint not null references public.wedding_sites (id) on delete cascade,
  first_name     text not null default '',
  last_name      text not null default '',
  email          text not null default '',
  attending      boolean not null default true,
  guests_count   integer not null default 1,
  children_count integer not null default 0,
  allergies      text not null default '',
  diet           text not null default '',
  housing        text not null default '',
  transport      text not null default '',
  message        text not null default '',
  events         jsonb,
  created_at     timestamptz not null default now()
);

create index if not exists rsvp_responses_site_idx on public.rsvp_responses (site_id, created_at desc);

-- Cagnottes et liste de mariage.
create table if not exists public.gift_options (
  id             bigint generated by default as identity primary key,
  site_id        bigint not null references public.wedding_sites (id) on delete cascade,
  gift_type      text not null default '',
  title          text not null default '',
  description    text not null default '',
  goal_amount    numeric not null default 0,
  current_amount numeric not null default 0,
  position       integer not null default 0
);

create index if not exists gift_options_site_idx on public.gift_options (site_id, position);

-- Bibliothèque de visuels (partagée entre les sites, ou importés par les mariés).
create table if not exists public.media_assets (
  id          bigint generated by default as identity primary key,
  category    text not null default '',
  title       text not null default '',
  url         text not null default '',
  collection  text not null default '',
  kind        text not null default 'photo',
  orientation text not null default 'paysage'
);

create index if not exists media_assets_category_idx on public.media_assets (category);

-- ----------------------------------------------------------------------------
--  Clés d’édition
--
--  Un jeton aléatoire par site, stocké sous forme d’empreinte SHA-256 : la
--  base ne contient jamais le secret en clair. Il est renvoyé une seule fois,
--  à la création (api/create-site.js), puis conservé par le navigateur.
--  Voir server/auth.js et la section « Sécurité » du README.
-- ----------------------------------------------------------------------------
-- Clés d’édition. Une ligne par site, créée en même temps que lui par
-- POST /api/create-site. `edit_token` ne contient QUE l’empreinte SHA-256 du
-- jeton : le clair n’est renvoyé qu’une fois, à la création, et n’est jamais
-- stocké côté serveur. Voir server/auth.js et la section « Exploitation ».
create table if not exists public.site_secrets (
  site_id    bigint primary key references public.wedding_sites (id) on delete cascade,
  edit_token text not null,           -- sha256(jeton) en hexadécimal, 64 caractères
  created_at timestamptz not null default now()
);

-- Bucket des images importées depuis l’éditeur (voir api/upload.js).
insert into storage.buckets (id, name, public)
values ('wedding-media', 'wedding-media', true)
on conflict (id) do nothing;

-- ============================================================================
--  Row Level Security
--
--  Les fonctions serverless utilisent la clé de service, qui contourne RLS :
--  activer RLS sans politique bloque uniquement les accès directs avec la clé
--  anonyme, ce qui est exactement ce que l’on veut — le navigateur ne parle
--  jamais à Supabase, seulement à /api/*.
--
--  L’éditeur est protégé par une clé (en-tête `x-site-token`, vérifiée côté
--  serveur dans server/auth.js) : n’ouvrez PAS RLS à des écritures anonymes,
--  cela court-circuiterait ce contrôle.
-- ============================================================================
do $$
declare
  t text;
begin
  foreach t in array array[
    'wedding_sites', 'site_sections', 'programme_events', 'infos_pratiques',
    'gallery_photos', 'faqs', 'rsvp_events', 'rsvp_responses', 'gift_options',
    'media_assets', 'site_secrets'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end
$$;

-- ============================================================================
--  Exploitation des clés d’édition
-- ============================================================================

-- Sites créés avant la mise en place des clés : leur en donner une.
-- Le jeton en clair est impossible à retrouver ensuite (empreinte seule) :
-- choisissez une valeur longue et aléatoire, puis saisissez-la sur
-- `/editeur/<ID>` — l’écran d’accès refusé propose un champ pour cela.
-- (Équivalent navigateur : localStorage "wedding-site:edit-tokens"
--  -> {"id:<ID>":"<JETON>"}.) Poser une nouvelle clé révoque l’ancienne.
--
-- insert into public.site_secrets (site_id, edit_token)
-- select w.id, encode(sha256('REMPLACER_PAR_UN_JETON'::bytea), 'hex')
-- from public.wedding_sites w
-- where not exists (select 1 from public.site_secrets s where s.site_id = w.id);

-- Clé perdue (nouveau navigateur, stockage effacé) : en poser une nouvelle.
--
-- update public.site_secrets
--    set edit_token = encode(sha256('NOUVEAU_JETON'::bytea), 'hex'),
--        created_at = now()
--  where site_id = 1;

-- Retrouver le site auquel appartient une clé :
-- select site_id from public.site_secrets
--  where edit_token = encode(sha256('JETON_SAISI'::bytea), 'hex');
